[RFC]Add an LLM engine
sgl-project/sglang pull request #1127
Opened 2024-08-16 17:19 UTC by JianyuZhan

## Motivation

This is not complete work, just a PoC and request for comment.

This PR adds a LLM engine, addressing the Roadmap item 'Add APIs for using the inference engine in a single script without launching a separate server.'

## Modification

It adds:

1. a core `Engine`, which wraps the core logic of what current `server.launch_server()` does, with addition of shutdown logic to gracefully bring down the `ZMQ` sockets in the `TokenizationManager` when finishing the job.
2. The 'class SamplingParams' is exposed as an API  now(The `GenerateReqInput` has a `dict` version of `SamplingParams`, which mandates a circuitous transform from class to dict then to class).
3. Along the way,  I also add `EngineArgs`, and make a new `ServerArgs` a thin wrapper of it(see `serving/engine_args.py` and `serving/server_args.py`), and some config objects from  `EngineArgs`, like `ModelConfig`, `ScheduleConfig`, `ParallelConfig`, etc, a mimic of vllm.  This opens up an opportunity to clean up of internal passing of `ServerArgs` arround many functions, and draw a more clean APIs for different sub-components.  But I didn't make this modification yet, it is quite intruisive to the current code base, thus I make this PR for RFC.

The demo usage is in `examples/usage/llm_engine.py`:

```
from sglang import LLM, SamplingParams

# Sample prompts.
prompts = [
    "Hello, my name is",
    "The capital of China is",
    "What is the meaning of life?",
    "The future of AI is",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

# Create an LLM.
llm = LLM(model="deepseek-ai/deepseek-llm-7b-chat")

outputs = llm.generate(prompts, sampling_params)
# Print the outputs.
for prompt, output in zip(prompts, outputs):
    print('===============================')
    print(f"Prompt: {prompt}\nGenerated text: {output['text']}")
```

## Checklist

- [ ] Before submitting a PR for review, make sure it has passed verification in your local development environment **at least**.
- [ ] Ensure pre-commit `pre-commit run --all-files` or other linting tools are used to fix potential lint issues.
- [ ] Confirm that modifications are covered by complete unit tests. If not, please add more unit tests for correctness.
- [ ] Modify documentation as needed, such as docstrings or example tutorials.

2024-08-17 02:17 UTC, Ying1123 reviewed
Thanks for your contribution! It looks good at a high level. My review is still in progress, and other committers will also take a look.

2024-08-17 02:17 UTC, Ying1123 commented on python/sglang/srt/managers/controller_multi.py
> +        nccl_ports: List[int],
Why expand the `port_args`?

2024-08-17 02:39 UTC, JianyuZhan commented on python/sglang/srt/managers/controller_multi.py
> +        nccl_ports: List[int],
I incorporate a higer level config object `ModelConfig` in `sglang/srt/config.py`,  and I think `PortArgs` is quite an ad-hoc abstraction compared to `ModelConfig`. I expand them now, hopefully it exposes opportunity to trainsit the internal code interface to use a more high-level and syntatic-complete abstraction. For example, see 

`glang/srt/serving/engine.py`

```
        # Launch processes
        self.tokenizer_manager = TokenizerManager(server_args, 
                                                  self.model_config.tokenizer_port,
                                                  self.model_config.controller_port, 
                                                  self.model_config.model_override_args)
```
If later we get rid of `server_args `, we can just pass in a `self.model_config`.  a `TokenizerManager` is quite naturally relying on a `ModelConfig`.

2024-08-17 05:25 UTC, JianyuZhan commented on python/sglang/srt/managers/controller_multi.py
> +        nccl_ports: List[int],
I pushed another [commit](https://github.com/sgl-project/sglang/pull/1127/commits/5fa229b9831bbbf10237f247adb78bc7f8ba05c8): `Get rid of server_args in internal iterfaces`. Now internal interface is `server_args`-free, and we pass in serveral `*Config` instead. 

Just PoC. Haven't gone through CI tests yet.

2024-08-17 12:29 UTC, zhyncs commented
@JianyuZhan Can you fully verify locally before committing now? I'm currently troubleshooting CI issues, which will be affected.

2024-08-18 05:19 UTC, JianyuZhan commented
Hi, @[Ying1123](https://github.com/Ying1123),  now this PR is complete, and passed all CI tests (except a test file import failure(the e2e-test), which runs ok on my local test, I am confused and didn’t find out what causes the discrepancy, would you mind helping take a look?).

This PR makes Modifications as below:

1. Added an `Engine` and `EngineArgs`, in parallel with `Server` and `ServerArgs` (all in `sglang/srt/serving/`). And now `ServerArgs` is a thin wrapper on `EngineArgs`, with server-specific args like port, and OpenAI API stuff.  And `ServerArgs` transparently pass all args in `EngineArgs` to it, rendering users a backward-compatible API.
2. Based on 1, we can now have two serving method. One is the old server api , and the other is the Engine API without running a server, see `examples/usage/llm_engine.py`.
3. Along the way, we can now get rid of `ServerArgs` in internal APIs(`mangers/`, `model_executor/`). Instead we incorporate `ModelConfig` , `ScheduleConfig`, `ParallelConfig`, `OptimizationConfig`, `ObservabilityConfig` (all created from `EngineArgs` and built upon `Engine` creation time). And those internal APIs are now communicating with each other using these `*Config` objects; and it results in a quite coherent interfaces , in sense of the component abastraction and its dependency.

2024-08-19 04:30 UTC, JianyuZhan commented
I have rebased upon the latest upstream/main branch, and it passed all CI tests now.

2024-08-21 07:25 UTC, zhyncs reviewed
I don't understand why the implementation related to `server` and `server args` under `srt` needs to be copied and rewritten in the `serving` folder.

2024-08-21 07:26 UTC, zhyncs commented
Your intention is to add an LLM Engine for offline use, may we just modify the necessary parts?

2024-08-21 07:28 UTC, zhyncs commented
Do we need to redo the abstractions? Can't we just wrap a layer around the original interface and implement the LLM Engine instead?

2024-08-21 07:52 UTC, zhyncs commented
One scenario where this API would be particularly useful is integrating it with the Triton Server Python Backend, similar to what's done here: https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/turbomind/triton_python_backend/model.py. In other situations, using OpenAI Server could be a better option. In the above example, the encapsulation of the `pipeline` and the calling of the `generate` interface are very appropriate. Perhaps we can take it as a reference?

2024-08-21 08:24 UTC, Ying1123 commented
I guess @JianyuZhan was trying to not affect the existing code. But we should just try to review carefully instead of open another code path. The design principle is to not duplicate the code. @JianyuZhan Could you try to reuse existing modules as much as possible?

2024-08-21 08:36 UTC, JianyuZhan commented
@zhyncs @Ying1123. Yes, the main goal is to provide a server-free (or offline) `Engine`, and the api is quite similar to the `triton_python_backend` you mentioned: https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/turbomind/triton_python_backend/model.py#L113. You can refer to `srt/serving/engine.py`.

This `Engine` abstraction naturally leads to separating the `Engine` (and its arguments) from the original `Server` and `ServerArgs`. Specifically, the `Server` is now built on top of the `Engine`.  See the new `launch_server()`:

```
def launch_server(
    server_args: ServerArgs,
    pipe_finish_writer: Optional[mp.connection.Connection] = None,
):
    """Launch an HTTP server."""

    logging.basicConfig(
        level=getattr(logging, server_args.log_level.upper()),
        format="%(message)s",
    )

    global engine
    engine = Engine.from_engine_args(server_args.engine_args)

    if server_args.chat_template:
        load_chat_template_for_openai_api(
            engine.tokenizer_manager, server_args.chat_template
        )

    if server_args.file_storage_pth:
        global file_storage_pth
        file_storage_pth = server_args.file_storage_pth

    # Add api key authorization
    if server_args.api_key:
        add_api_key_middleware(app, server_args.api_key)

    # Send a warmup request
    t = threading.Thread(
        target=_wait_and_warmup, args=(server_args, pipe_finish_writer, os.getpid())
    )
    t.start()

    try:
        # Listen for requests
        uvicorn.run(
            app,
            host=server_args.host,
            port=server_args.port,
            log_level=server_args.log_level_http or server_args.log_level,
            timeout_keep_alive=5,
            loop="uvloop",
        )
    finally:
        t.join()
```

 Along this route, I found making the internal components  `Engine-centric` is more tuititive.  Thus I pushed the the second commit, "get rid of server args," which removes the `Server-centric` API in the internal components. And it turns out a quite cleaner API. But this second commit is mainly what I call this PR as RFC, and I just bring it up for discussion. And of course, we could still retain the server-centric abstraction.

2024-08-21 09:06 UTC, JianyuZhan commented
@Ying1123 , I did try to reuse most current code. The addition/deleltion line comparsion is dauting, mostly because I forgot to remove the old  `serer*py`, and now I re-push the new code..  Most of the change is just s/server_args/*config/g to get rid of the old `server_args`.  I think most of the code logic is instact but just the interface changes.  Hopefully I have clarified  my intention in this PR.  And if you prefer to retrain the server_args, I can rework another version.

2024-08-29 05:06 UTC, DragonFive commented
@JianyuZhan  Hi, I try use your repo to test, I clone the code wite main branch , and run
```bash
pip install -e "python[all]"
pip install flashinfer -i https://flashinfer.ai/whl/cu118/torch2.4/
```
but when I run follow test
```python
from sglang import LLM, SamplingParams
```
but is says
```bash
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from sglang import LLM, SamplingParams

ImportError: cannot import name 'LLM' from 'sglang' (unknown location)
```

How can i fix it, looking for your help!

2024-08-29 05:39 UTC, JianyuZhan commented
@DragonFive ,  Add "LLM" and "SamplingParams"  in `sglang/__init__.py::__all__`, it is now imported in this __init__.py but not exposed, or you can try `from sglang.api  import LLM, SamplingParams`. The code lags behind upstream and I will later rebase and repush.
`

2024-08-29 07:36 UTC, DragonFive commented
> @DragonFive , Add "LLM" and "SamplingParams" in `sglang/__init__.py::__all__`, it is now imported in this **init**.py but not exposed, or you can try `from sglang.api import LLM, SamplingParams`. The code lags behind upstream and I will later rebase and repush. `

It works fine for me, thanks for your contribution!

2024-08-29 18:27 UTC, jischein commented
Running into the following issues with `tp_worker` when trying to query Llama 3.1 405B FP8 on an 8xH100 while setting `tensor_parallel_size=8`.  
```
llm = LLM(model="meta-llama/Meta-Llama-3.1-405B-Instruct-FP8", tensor_parallel_size=8)
prompts = ["Hello, my name is"]
res = llm.generate(prompts)
[18:19:55 TP0] Decode batch. #running-req: 1, #token: 85, token usage: 0.00, gen throughput (token/s): 32.43, #queue-req: 0
[18:19:57 TP0] Decode batch. #running-req: 1, #token: 125, token usage: 0.00, gen throughput (token/s): 32.32, #queue-req: 0
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[18:19:57 TP2] Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.233.87.118]:9425: Connection reset by peer

Process Process-1:2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.233.87.118]:9425: Connection reset by peer
[18:19:57 TP1] Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.233.87.118]:59799: Connection reset by peer

[18:19:57 TP4] Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.233.87.118]:43139

Process Process-1:1:
Process Process-1:4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
Traceback (most recent call last):
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.233.87.118]:59799: Connection reset by peer
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.233.87.118]:43139
[18:19:57 TP6] Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.233.87.118]:37813

Process Process-1:6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.2 [...]

2024-08-30 03:01 UTC, JianyuZhan commented
@jischein , Thanks for testing. I don't have this multi-GPU environment to test. Per my analysis, your error looks like the `tp procs` are not terminated properly in `Engine::shutdown()` . I tried to fix it, would you mind testing the new code I just pushed?

2024-08-30 06:53 UTC, feifei-111 commented
this PR will raise "AttributeError: 'Engine' object has no attribute 'tp_procs'" when do inference with one gpu, need add self.tp_procs=None in Engine.startup

2024-09-01 17:47 UTC, jischein requested changes

2024-09-01 17:47 UTC, jischein commented on python/sglang/srt/model_executor/model_runner.py
> +        if self.model_config.model_overide_args is not None:
This should be `model_override_args`; I tried compiling the engine with tp=8 and got

```
>>> from sglang import LLM, SamplingParams
>>> llm = LLM(model="meta-llama/Meta-Llama-3.1-405B-Instruct-FP8", tensor_parallel_size=8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sglang/python/sglang/srt/serving/engine.py", line 190, in __init__
    self.llm_engine = Engine(engine_args)
  File "/home/ubuntu/sglang/python/sglang/srt/serving/engine.py", line 50, in __init__
    self.startup()
  File "/home/ubuntu/sglang/python/sglang/srt/serving/engine.py", line 89, in startup
    self.tokenizer_manager = TokenizerManager(self.engine_args)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 93, in __init__
    self.hf_config = get_config(
TypeError: get_config() got an unexpected keyword argument 'model_overide_args'
>>>
```

2024-09-01 17:47 UTC, jischein commented on python/sglang/srt/managers/tokenizer_manager.py
> +            model_overide_args=engine_args.model_override_args,
same here; this should be `model_override_args` to match fn signature in `get_config`

2024-09-01 17:47 UTC, jischein commented on python/sglang/srt/managers/controller_multi.py
> +        self.model_overide_args = engine_args.model_override_args
here too

2024-09-01 17:47 UTC, jischein commented on python/sglang/srt/managers/tp_worker.py
> +            model_overide_args=engine_args.model_override_args,
here as well

2024-09-01 17:56 UTC, jischein commented
@JianyuZhan unfortunately still running into errors after cleaning up the typos
```
>>> prompts = ["Hi my name is"]
>>> res=llm.generate(prompts)
[17:53:56 TP0] Prefill batch. #new-seq: 1, #new-token: 5, #cached-token: 0, cache hit rate: 0.00%, #running-req: 0, #queue-req: 0
[17:53:57 TP0] Decode batch. #running-req: 1, #token: 45, token usage: 0.00, gen throughput (token/s): 0.49, #queue-req: 0
[17:53:58 TP0] Decode batch. #running-req: 1, #token: 85, token usage: 0.00, gen throughput (token/s): 32.50, #queue-req: 0
[17:54:00 TP0] Decode batch. #running-req: 1, #token: 125, token usage: 0.00, gen throughput (token/s): 32.47, #queue-req: 0
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[17:54:00 TP1] Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.233.87.118]:51919: Connection reset by peer

Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.233.87.118]:51919: Connection reset by peer
[17:54:00 TP2] Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 892, in run_tp_server
    recv_reqs = broadcast_recv_input(None, tp_rank, tp_cpu_group)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/tp_worker.py", line 938, in broadcast_recv_input
    dist.broadcast(tensor_size, src=0, group=dist_group)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/opt/vllm-foundry/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2213, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [10.233.87.118]:2179: Connection reset by peer

2024-09-01 18:03 UTC, jischein commented
https://github.com/JianyuZhan/sglang/pull/1 — @JianyuZhan this compiles / addresses the typo

2024-09-02 01:58 UTC, DragonFive commented
> [JianyuZhan#1](https://github.com/JianyuZhan/sglang/pull/1) — @JianyuZhan this compiles / addresses the typo

Change all the 'model_overide_args'  to 'model_override_args' in the repo will work well.

2024-09-06 02:57 UTC, DragonFive commented
@JianyuZhan  It runs well before I ungrade sglang to v0.3.0 on llama3.1-8b, after that I encounter some confused error ：

```bash
10:46:19.553 [10:46:19 TP0] Exception in ControllerSingle:
10:46:19.553 Traceback (most recent call last):
10:46:19.553   File "/github_sglang/python/sglang/srt/managers/controller_single.py", line 157, in start_controller_process
10:46:19.553     controller.loop_for_forward()
10:46:19.553   File "/github_sglang/python/sglang/srt/managers/controller_single.py", line 98, in loop_for_forward
10:46:19.553     out_pyobjs = self.tp_server.exposed_step(recv_reqs)
10:46:19.553   File "/github_sglang/python/sglang/srt/managers/tp_worker.py", line 243, in exposed_step
10:46:19.553     self.forward_step()
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
10:46:19.553     return func(*args, **kwargs)
10:46:19.553   File "/github_sglang/python/sglang/srt/managers/tp_worker.py", line 259, in forward_step
10:46:19.553     self.forward_prefill_batch(new_batch)
10:46:19.553   File "/github_sglang/python/sglang/srt/managers/tp_worker.py", line 506, in forward_prefill_batch
10:46:19.553     sample_output, logits_output = self.model_runner.forward(
10:46:19.553   File "/github_sglang/python/sglang/srt/model_executor/model_runner.py", line 591, in forward
10:46:19.553     return self.forward_extend(batch)
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
10:46:19.553     return func(*args, **kwargs)
10:46:19.553   File "/github_sglang/python/sglang/srt/model_executor/model_runner.py", line 555, in forward_extend
10:46:19.553     return self.model.forward(
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
10:46:19.553     return func(*args, **kwargs)
10:46:19.553   File "/github_sglang/python/sglang/srt/models/llama.py", line 317, in forward
10:46:19.553     hidden_states = self.model(input_ids, positions, input_metadata, input_embeds)
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
10:46:19.553     return self._call_impl(*args, **kwargs)
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
10:46:19.553     return forward_call(*args, **kwargs)
10:46:19.553   File "/github_sglang/python/sglang/srt/models/llama.py", line 282, in forward
10:46:19.553     hidden_states, residual = layer(
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
10:46:19.553     return self._call_impl(*args, **kwargs)
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
10:46:19.553     return forward_call(*args, **kwargs)
10:46:19.553   File "/github_sglang/python/sglang/srt/models/llama.py", line 232, in forward
10:46:19.553     hidden_states = self.self_attn(
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
10:46:19.553     return self._call_impl(*args, **kwargs)
10:46:19.553   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
10:46:19.553     return forward_call(*args, **kwargs)
10:46:19.554   File "/github_sglang/python/sglang/srt/models/llama.py", line 168, in forward
10:46:19.554     q, k = self.rotary_emb(positions, q, k)
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
10:46:19.554     return self._call_impl(*args, **kwargs)
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
10:46:19.554     return forward_call(*args, **kwargs)
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/vllm/model_executor/custom_op.py", line 14, in forward
10:46:19.554     return self._forward_method(*args, **kwargs)
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 216, in forward_cuda
10:46:19.554     ops.rotary_embedding(positions, query, key, self.head_size,
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/vllm/_custom_ops.py", line 37, in wrapper
10:46:19.554     raise e
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/vllm/_custom_ops.py", line 28, in wrapper
10:46:19.554     return fn(*args, **kwargs)
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/vllm/_custom_ops.py", line 138, in rotary_embedding
10:46:19.554     torch.ops._C.rotary_embedding(positions, query, key, head_size,
10:46:19.554   File "/usr/local/lib/python3.9/site-packages/torch/_ops.py", line 1170, in __getattr__
10:46:19.554     raise AttributeError(
10:46:19.554 AttributeError: '_OpNamespace' '_C' object has no attribute 'rotary_embedding'
```

2024-09-06 03:20 UTC, JianyuZhan commented
@DragonFive it is because the vllm dependency is upgraded, I think, you shall update your local installation dependency as well: `pip install --upgrade pip
pip install -e "python[all]"`, cf the install section in the README.

2024-09-07 14:22 UTC, yangky11 commented
Hi, thank you for this PR. I'm looking forward to trying it out. I'm wondering if there is plan to support asynchronous operations similar to [vllm. AsyncLLMEngine](https://docs.vllm.ai/en/latest/dev/engine/async_llm_engine.html).

2024-09-08 20:44 UTC, zhyncs commented
> Hi, thank you for this PR. I'm looking forward to trying it out. I'm wondering if there is plan to support asynchronous operations similar to [vllm. AsyncLLMEngine](https://docs.vllm.ai/en/latest/dev/engine/async_llm_engine.html).

Hi @yangky11 Maybe you can try this https://github.com/sgl-project/sglang/blob/05bea6883c4b3f2fb7f01287cd8dccefeacd545f/python/sglang/srt/server.py#L562

2024-09-13 20:25 UTC, jischein commented
@JianyuZhan @zhyncs is this close to being merged? Would love to use ! :)

2024-10-06 01:09 UTC, merrymercy commented
moved to #1567

2024-10-06 01:09 UTC, closed without merging

2024-10-06 01:11 UTC, zhyncs commented
Although this PR was closed, we still appreciate @JianyuZhan 's contribution. Thanks!