Support Alibaba-NLP/gte-Qwen2-7B-instruct Model
sgl-project/sglang pull request #1186
Opened 2024-08-22 15:03 UTC by zhaochenyang20

## Motivation

Current SGLang only supports the e5-mistral embedding model. I added Alibaba-NLP/gte-Qwen2-7B-instruct model in this PR. 

Also, previously SGLang determines a model as an embedding model through its `hf_config.architectures`. But gte model has the same architecture as CausalLM. So I added a new parameter in the `server_args` and changed the forward function of `Qwen2ForCausalLM`.

## Modifications

1. Changed the forward function of `Qwen2ForCausalLM`.
2. Added a new parameter `is_embedding` in `server_args`.
3. Some related changes.
4. Added unit tests for gte models.
5. Changed readme.

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

2024-08-23 03:10 UTC, Ying1123 requested changes

2024-08-23 03:10 UTC, Ying1123 commented on README.md
> +**Completion Models**
```suggestion
**Generative Models**
```

2024-08-23 03:10 UTC, Ying1123 commented on README.md
> +  - `python -m sglang.launch_server --model-path intfloat/e5-mistral-7b-instruct --is-embedding`
```suggestion
  - `python -m sglang.launch_server --model-path Alibaba-NLP/gte-Qwen2-7B-instruct --is-embedding`
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/server_args.py
> +            default=False,
```suggestion
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/managers/tokenizer_manager.py
> +        assert self.server_args.is_embedding is not None
```suggestion
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/managers/tokenizer_manager.py
> +            self.hf_config.architectures, self.server_args
```suggestion
            self.hf_config.architectures, self.server_args.is_embedding
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/utils.py
> +def is_generation_model(model_architectures, server_args=None):
```suggestion
def is_generation_model(model_architectures, is_embedding=False):
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/utils.py
> +    # 1. Check if the architectue
```suggestion
    # 1. Check the model architectue
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/utils.py
> +    # We have two ways to determine whether a model is a generation model.
```suggestion
    # We have two ways to determine whether a model is a generative model.
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/utils.py
> +    # 2. check the server args
```suggestion
    # 2. check the `is_embedding` in server args
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/utils.py
> +        return not server_args.is_embedding
```suggestion
    return not server_args.is_embedding
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/utils.py
>      return True
```suggestion
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/managers/tp_worker.py
> +
```suggestion
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/managers/tp_worker.py
> +
```suggestion
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/model_executor/model_runner.py
> +            self.model_config.hf_config.architectures, self.server_args
```suggestion
            self.model_config.hf_config.architectures, self.server_args.is_embedding
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/model_executor/model_runner.py
> +        if self.is_generation == True:
```suggestion
        if self.is_generation:
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/models/qwen2.py
> +            )
Change the order of two branches. We always choose the generation branch as the first one.

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/server.py
> +        #! 这里 launch 了 tp server
```suggestion
```

2024-08-23 03:10 UTC, Ying1123 commented on python/sglang/srt/server.py
> +        assert self.server_args.is_embedding is not None, "is_embedding must be set."
```suggestion
```

2024-08-23 03:10 UTC, Ying1123 commented on test/srt/models/test_generation_models.py
Add `Alibaba-NLP/gte-Qwen2-1.5B-instruct` to this test.

2024-08-23 07:24 UTC, zhaochenyang20 commented
@Ying1123 I added gte in the generation model test. Note that I changed the prefill tolerance accordingly and added the rouge-l metric instead of assert output_strs exactly the same.

2024-08-24 18:37 UTC, Ying1123 approved these changes

2024-08-25 07:28 UTC, Ying1123 approved these changes

2024-08-25 17:29 UTC, merged

2024-08-26 00:20 UTC, hnyls2002 commented on test/srt/models/test_generation_models.py
> +            mp.set_start_method("spawn")
Why would this be needed?

2024-08-28 06:25 UTC, llmforever commented
different result compare with orginal hf back end,why?

prompt = “hello world”
sglang:
import openai
client = openai.Client(
    base_url="http://localhost:30000/v1", api_key="EMPTY")

response = client.embeddings.create(
    model="default",
    input=prompt ,
)

transformer：
tokenizer = AutoTokenizer.from_pretrained('Alibaba-NLP/gte-Qwen2-7B-instruct', trust_remote_code=True)
model = AutoModel.from_pretrained('Alibaba-NLP/gte-Qwen2-7B-instruct', trust_remote_code=True)

max_length = 8192

# Tokenize the input texts
batch_dict = tokenizer(prompt, max_length=max_length, padding=True, truncation=True, return_tensors='pt')
outputs = model(**batch_dict)
embeddings = last_token_pool(outputs.last_hidden_state, batch_dict['attention_mask'])

# normalize embeddings
embeddings = F.normalize(embeddings, p=2, dim=1)

2024-09-01 23:55 UTC, zhaochenyang20 commented
@llmforever hello. Sorry, I haven't noticed this before. Do you still need to fix this? Actually, we have a unit test for this in `test/srt/models/test_embedding_models.py`. The logits here is indeed closed.

Also, I don't understand what did you mean by "perform not so well". Could you provide your running snifts and your serving command for SGLang.

And, does e5-mistral also have this problem? Or only get?

2024-09-02 05:30 UTC, thomZ1 commented
![image](https://github.com/user-attachments/assets/6c3ff962-9e62-458b-841a-3e390349724a)
The same problem, I tried using the SGLang OpenAI API and SentenceTransformer with the same prompt, but the output embeddings were different.

2024-09-02 09:41 UTC, zhaochenyang20 commented
Yeah. The embedding could be different due to a lot of reasons. @llmforever 

You can check this unit test: https://github.com/sgl-project/sglang/blob/main/test/srt/models/test_embedding_models.py

We set a tolerance value for the embedding difference.

Also, please try the e5-mistral model and give us the embedding difference. 

https://huggingface.co/intfloat/e5-mistral-7b-instruct

@Ying1123 Do you think the difference provided is tolerable?

2024-09-04 11:45 UTC, llmforever commented
> Yeah. The embedding could be different due to a lot of reasons. @llmforever
> 
> You can check this unit test: https://github.com/sgl-project/sglang/blob/main/test/srt/models/test_embedding_models.py
> 
> We set a tolerance value for the embedding difference.
> 
> Also, please try the e5-mistral model and give us the embedding difference.
> 
> https://huggingface.co/intfloat/e5-mistral-7b-instruct
> 
> @Ying1123 Do you think the difference provided is tolerable?

I test about 10 cases，**each accuracy drop from 80% to less than 10%**，i think the difference is not tolerable，but the result of the e5-mistral-7b-instruct model is the same，can you please help me look that? Here is the code i use to generate the embedding：

**for transformer：**

import torch
import torch.nn.functional as F

from torch import Tensor
from transformers import AutoTokenizer, AutoModel

input_texts = ['hello']
tokenizer = AutoTokenizer.from_pretrained('Alibaba-NLP/gte-Qwen2-7B-instruct', trust_remote_code=True)
model = AutoModel.from_pretrained('Alibaba-NLP/gte-Qwen2-7B-instruct', trust_remote_code=True)

max_length = 8192

batch_dict = tokenizer(input_texts, max_length=max_length, padding=True, truncation=True, return_tensors='pt')
outputs = model(**batch_dict)
embeddings = last_token_pool(outputs.last_hidden_state, batch_dict['attention_mask'])

# normalize embeddings
embeddings = F.normalize(embeddings, p=2, dim=1)

**for sglang:**
import openai
import time
client = openai.Client(
    base_url="http://localhost:30000/v1", api_key="EMPTY")

input_texts = ['hello']

queres = client.embeddings.create(
    model="default",
    input=quelist,
)
embeddings  = torch.tensor(response.data[0].embedding)

2024-09-04 13:43 UTC, zhaochenyang20 commented
@Ying1123 I think he provides an intolerable difference hummm?  I gonna check it these days.