[WIP] Spec infer with EAGLE2
sgl-project/sglang pull request #1498
Opened 2024-09-24 07:46 UTC by yukavio

## Motivation
Accelerate the model inference by speculative inference (EAGLE2).

## Modifications
It will be provided soon.

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

2024-09-26 05:45 UTC, Qiubo1 commented
hello, whether this code supports the multiple request sepc?

2024-10-09 13:33 UTC, fengyang95 commented
Hi @yukavio Is there any recent progress or plan for this?

2024-10-11 12:49 UTC, yukavio commented
> hello, whether this code supports the multiple request sepc?

Yes, I will support it.

2024-10-11 12:58 UTC, yukavio commented
> Hi @yukavio Is there any recent progress or plan for this? Do you plan to support deepseek-v2?

I have implemented the draft and verify stages and tested them on a single request.  I am trying to migrate my code to the main branch due to the main branch has some significant changes about the controller and worker which are very important for my implementation. 

My plan:
Migrate code and test it: 1-2 days.
Implement remained code of single request speculative decoding:  half or one week.
Implement remained code of speculative decoding with batch: one or two week.

2024-10-16 03:47 UTC, Qiubo1 commented
THX, yukavio.I have some suggestions for this pr: 1. further more support more models, e.g. i think we should pop the eagle head from draft_extend_input_queue so we dont modify the origin llama model file. 2.i dont understand why we need so many SpecInfoPipline queue, spec only in decoding stage,if we dont need the draft_extend_input_queue at least.

2024-10-16 08:40 UTC, Qiubo1 commented
Also i have another question, in the pr model_runner.py init kv cache twice in different tpworker, this results in the oom in gpu, if  we merge the draft and tagret kv cache to increase the gpu utilization?

2024-10-16 10:57 UTC, yukavio commented
> Also i have another question, in the pr model_runner.py init kv cache twice in different tpworker, this results in the oom in gpu, if we merge the draft and tagret kv cache to increase the gpu utilization?

I have migrated the code to another branch :https://github.com/yukavio/sglang/tree/new_spec_infer and I will update the code to this PR lately. In the new implementation, I choose to run the draft worker and target model worker in one process instead of using many queues in SpecInfoPipline to communicate with draft work process and target process.

For memory management, I've fixed this bug in the new branch to ensure it won't raise an error during testing. But it may not be very efficient and I will improve it after I have finish the remained work in the plan.

2024-10-21 04:09 UTC, zhyncs commented
@yukavio Hi yukavio Recently, SGLang has undergone some refactoring work. You need to merge the latest main to resolve the corresponding conflicts. Thanks!

2024-10-21 07:02 UTC, fengyang95 commented
@yukavio Hi, when is this PR expected to be merged? I've trained a draft model and am eager to try it out.

2024-10-21 11:22 UTC, yukavio commented
> @yukavio Hi yukavio Recently, SGLang has undergone some refactoring work. You need to merge the latest main to resolve the corresponding conflicts. Thanks!

OK, I am fixing some bugs in batch inference now. I will update the code to main branch after fixing them. Personally, I think the updated code can be used as the first version. The community could review this version of the implementation.

2024-10-21 11:24 UTC, yukavio commented
> @yukavio Hi, when is this PR expected to be merged? I've trained a draft model and am eager to try it out.

If all goes well I will finish the first version of development this week. When to merge into the main branch depends on community review and opinions.

2024-10-23 02:54 UTC, yukavio commented
I have updated the code. The new implementation has support draft model inference with cuda graph / speculative inference with batch. It can been tested by run `python examples/runtime/engine/offline_batch_inference.py`. 
TODO:
1. To support more sampling arguments. (Only support greedy now)
2. Migrate the code and fix conflict.
3. Performance improvement.
    1.  Write some kernel to fuse the element-wise operation in EAGLE Tree building to accelerate it.
    2. Try to overlap the progress of model inference and EAGLE Tree building and verify progress.

2024-10-23 15:07 UTC, fengyang95 commented
@yukavio Is CLI startup not supported currently? I encountered this error:
```python
File "/opt/tiger/sglang/python/sglang/srt/server_args.py", line 613, in <dictcomp>
return cls(**{attr: getattr(args, attr) for attr in attrs})
^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'draft_runner_cache_size'
```

2024-10-24 03:06 UTC, zhyncs commented
@yukavio Please fix the conflicts

2024-10-24 03:09 UTC, yukavio commented
> @yukavio Is CLI startup not supported currently? I encountered this error:
> 
> ```python
> File "/opt/tiger/sglang/python/sglang/srt/server_args.py", line 613, in <dictcomp>
> return cls(**{attr: getattr(args, attr) for attr in attrs})
> ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Namespace' object has no attribute 'draft_runner_cache_size'
> ```

Did your locally installed code switch to this branch? This error doesn't look like it should occur. Because I have already added this variable in server args.
https://github.com/sgl-project/sglang/pull/1498/files#diff-700b5118b493d60d7b5994857f5f1e6a7e842ad702392b8ab199945764dfc8edR123

And you can update the code for this branch because I just fixed a memory leak bug in batch inference.

2024-10-24 04:03 UTC, yukavio commented
> @yukavio Please fix the conflicts
OK, I am doing this.

2024-10-24 08:27 UTC, fengyang95 commented
> > @yukavio Is CLI startup not supported currently? I encountered this error:
> > ```python
> > File "/opt/tiger/sglang/python/sglang/srt/server_args.py", line 613, in <dictcomp>
> > return cls(**{attr: getattr(args, attr) for attr in attrs})
> > ^^^^^^^^^^^^^^^^^^^
> > AttributeError: 'Namespace' object has no attribute 'draft_runner_cache_size'
> > ```
> 
> Did your locally installed code switch to this branch? This error doesn't look like it should occur. Because I have already added this variable in server args. https://github.com/sgl-project/sglang/pull/1498/files#diff-700b5118b493d60d7b5994857f5f1e6a7e842ad702392b8ab199945764dfc8edR123
> 
> And you can update the code for this branch because I just fixed a memory leak bug in batch inference.

@yukavio  I am using the latest code. This is my startup script, is there anything wrong with it?:
```bash
python3 -m sglang.launch_server --model $LOCAL_PATH --stream-interval 1 --max-prefill-tokens 16384  --trust-remote-code  --mem-frac $MEM_FRAC --tp $TP_SIZE --dp $DP_SIZE --kv-cache-dtype fp8_e5m2 --port $PORT0  --mem-fraction-static $MEM_FRACTION_STATIC --schedule-conservativeness $SCHEDULE_CONSERVATIVENESS --context-length $MODEL_LEN  --chunked-prefill-size $CHUNKED_PREFILL_SIZE \
        --draft-model-path /opt/tiger/eagle --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE >> server.log 2>&1
```

2024-10-25 02:48 UTC, yukavio commented
> ```shell
> python3 -m sglang.launch_server --model $LOCAL_PATH --stream-interval 1 --max-prefill-tokens 16384  --trust-remote-code  --mem-frac $MEM_FRAC --tp $TP_SIZE --dp $DP_SIZE --kv-cache-dtype fp8_e5m2 --port $PORT0  --mem-fraction-static $MEM_FRACTION_STATIC --schedule-conservativeness $SCHEDULE_CONSERVATIVENESS --context-length $MODEL_LEN  --chunked-prefill-size $CHUNKED_PREFILL_SIZE \
>         --draft-model-path /opt/tiger/eagle --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE >> server.log 2>&1
> ```

Sorry, I haven't tested it as a service before. You can start the service with this command: python3 -m sglang.launch_server --model Llama-2-7b-chat-hf  --stream-interval 1 --max-prefill-tokens 16384  --trust-remote-code  --mem-frac 0.8 --tp 1 --dp 1   --mem-fraction-static 0.8   --draft-model-path EAGLE-llama2-chat-7B  --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE. However, I found that there seems to be some problems with the return value in this way. I will fix this error later. If you want to test, please run it first through the form in offline_batch_inference.py. This PR is not ready now. I'm doing more testing and fixing the bugs I find.

2024-10-25 07:46 UTC, fengyang95 commented
> > ```shell
> > python3 -m sglang.launch_server --model $LOCAL_PATH --stream-interval 1 --max-prefill-tokens 16384  --trust-remote-code  --mem-frac $MEM_FRAC --tp $TP_SIZE --dp $DP_SIZE --kv-cache-dtype fp8_e5m2 --port $PORT0  --mem-fraction-static $MEM_FRACTION_STATIC --schedule-conservativeness $SCHEDULE_CONSERVATIVENESS --context-length $MODEL_LEN  --chunked-prefill-size $CHUNKED_PREFILL_SIZE \
> >         --draft-model-path /opt/tiger/eagle --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE >> server.log 2>&1
> > ```
> 
> Sorry, I haven't tested it as a service before. You can Download the draft model(https://huggingface.co/yuhuili/EAGLE-llama2-chat-7B) first and edit the config (change architectures from "LlamaForCausalLM" to "LlamaForCausalLMEagle". After that, you can start the service with this command: `python3 -m sglang.launch_server --model Llama-2-7b-chat-hf --stream-interval 1 --max-prefill-tokens 16384 --trust-remote-code --mem-frac 0.8 --tp 1 --dp 1 --mem-fraction-static 0.8 --draft-model-path EAGLE-llama2-chat-7B --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE`
> 
> However, I found that there seems to be some problems with the return value in this way. I will fix this error later. If you want to test, please run it first through the form in offline_batch_inference.py.
> 
> This PR is not ready now. I'm doing more testing and fixing the bugs I find.

@yukavio 
After solving the issue mentioned above, a new problem has emerged.
[15:16:50 TP4] Traceback (most recent call last):
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1075, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
    self.tp_worker = TpModelWorker(
                     ^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
    self.init_cuda_graphs()
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 501, in init_cuda_graphs
    self.cuda_graph_runner = CudaGraphRunner(self)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 165, in __init__
    self.capture()
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 194, in capture
    ) = self.capture_one_batch_size(bs, num_token, forward)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 217, in capture_one_batch_size
    self.model_runner.attn_backend.init_forward_metadata_capture_cuda_graph(
TypeError: TritonAttnBackend.init_forward_metadata_capture_cuda_graph() takes 4 positional arguments but 5 were given

/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
  warnings.warn('resource_tracker: process died unexpectedly, '
Traceback (most recent call last):
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/mp-0aw9znwq'

2024-10-27 02:50 UTC, fengyang95 commented
> > ```shell
> > python3 -m sglang.launch_server --model $LOCAL_PATH --stream-interval 1 --max-prefill-tokens 16384  --trust-remote-code  --mem-frac $MEM_FRAC --tp $TP_SIZE --dp $DP_SIZE --kv-cache-dtype fp8_e5m2 --port $PORT0  --mem-fraction-static $MEM_FRACTION_STATIC --schedule-conservativeness $SCHEDULE_CONSERVATIVENESS --context-length $MODEL_LEN  --chunked-prefill-size $CHUNKED_PREFILL_SIZE \
> >         --draft-model-path /opt/tiger/eagle --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE >> server.log 2>&1
> > ```
> 
> Sorry, I haven't tested it as a service before. You can Download the draft model(https://huggingface.co/yuhuili/EAGLE-llama2-chat-7B) first and edit the config (change architectures from "LlamaForCausalLM" to "LlamaForCausalLMEagle". After that, you can start the service with this command: `python3 -m sglang.launch_server --model Llama-2-7b-chat-hf --stream-interval 1 --max-prefill-tokens 16384 --trust-remote-code --mem-frac 0.8 --tp 1 --dp 1 --mem-fraction-static 0.8 --draft-model-path EAGLE-llama2-chat-7B --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE`
> 
> However, I found that there seems to be some problems with the return value in this way. I will fix this error later. If you want to test, please run it first through the form in offline_batch_inference.py.
> 
> This PR is not ready now. I'm doing more testing and fixing the bugs I find.

@yukavio  When using the offline_batch_inference.py, I encountered the following error:
[23:23:54 TP7] Traceback (most recent call last):
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1085, in run_scheduler_process
    scheduler.event_loop()
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 272, in event_loop
    self.run_step()
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 459, in run_step
    result = self.run_batch(new_batch)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 669, in run_batch
    logits_output, next_token_ids = self.draft_worker.forward_batch_speculative_generate(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 67, in forward_batch_speculative_generate
    self.forward_draft_extend(batch)
  File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 42, in forward_draft_extend
    logits_output = self.model_runner.forward(forward_batch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 536, in forward
    return self.forward_extend(forward_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 520, in forward_extend
    return self.model.forward(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 328, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 289, in forward
    torch.cat(
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 44 but got size 1 for tensor number 1 in the list.

2024-10-28 06:56 UTC, yukavio commented
> > > ```shell
> > > python3 -m sglang.launch_server --model $LOCAL_PATH --stream-interval 1 --max-prefill-tokens 16384  --trust-remote-code  --mem-frac $MEM_FRAC --tp $TP_SIZE --dp $DP_SIZE --kv-cache-dtype fp8_e5m2 --port $PORT0  --mem-fraction-static $MEM_FRACTION_STATIC --schedule-conservativeness $SCHEDULE_CONSERVATIVENESS --context-length $MODEL_LEN  --chunked-prefill-size $CHUNKED_PREFILL_SIZE \
> > >         --draft-model-path /opt/tiger/eagle --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE >> server.log 2>&1
> > > ```
> > 
> > 
> > Sorry, I haven't tested it as a service before. You can Download the draft model(https://huggingface.co/yuhuili/EAGLE-llama2-chat-7B) first and edit the config (change architectures from "LlamaForCausalLM" to "LlamaForCausalLMEagle". After that, you can start the service with this command: `python3 -m sglang.launch_server --model Llama-2-7b-chat-hf --stream-interval 1 --max-prefill-tokens 16384 --trust-remote-code --mem-frac 0.8 --tp 1 --dp 1 --mem-fraction-static 0.8 --draft-model-path EAGLE-llama2-chat-7B --num-speculative-steps 5 --eagle-topk 8 --num-draft-tokens 64 --speculative-algorithm EAGLE`
> > However, I found that there seems to be some problems with the return value in this way. I will fix this error later. If you want to test, please run it first through the form in offline_batch_inference.py.
> > This PR is not ready now. I'm doing more testing and fixing the bugs I find.
> 
> @yukavio When using the offline_batch_inference.py, I encountered the following error:
> 
> ```shell
> [23:23:54 TP7] Traceback (most recent call last):
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1085, in run_scheduler_process
>     scheduler.event_loop()
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 272, in event_loop
>     self.run_step()
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 459, in run_step
>     result = self.run_batch(new_batch)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 669, in run_batch
>     logits_output, next_token_ids = self.draft_worker.forward_batch_speculative_generate(
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 67, in forward_batch_speculative_generate
>     self.forward_draft_extend(batch)
>   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 42, in forward_draft_extend
>     logits_output = self.model_runner.forward(forward_batch)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 536, in forward
>     return self.forward_extend(forward_batch)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 520, in forward_extend
>     return self.model.forward(
>            ^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 328, in forward
>     hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 289, in forward
>     torch.cat(
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 44 but got size 1 for tensor number 1 in the list.
> ```

Sorry, I'm fixing some bugs. This may cause the code to be temporarily unavailable, I will let you know here once I have fixed it and tested it.

2024-10-28 14:28 UTC, coolhok commented
Polite, may I ask if the build_tree function does not have a Triton version implementation！

2024-10-28 16:07 UTC, yukavio commented
> Polite, may I ask if the build_tree function does not have a Triton version implementation！
This kernel is difficult to implement with triton because triton don't support control the behavior of cuda threads.

2024-10-29 06:43 UTC, yukavio commented
@fengyang95  you can pull the new code and run offline_batch_inference.py again.

2024-10-29 08:20 UTC, fengyang95 commented
> @fengyang95 You can pull the new code and run offline_batch_inference.py again. It is my code to create Engine with EAGLE:
> 
> ```
> sgl.Engine(model_path="Llama-2-7b-chat-hf", draft_model_path='EAGLE-llama2-chat-7B', disable_cuda_graph=False, 
>                      num_speculative_steps=2, eagle_topk=2, num_draft_tokens=2,  speculative_algorithm='EAGLE', mem_fraction_static=0.75, 
>                      dtype='bfloat16')
> ```
> 
> You can change the argument of num_speculative_steps / eagle_topk / num_draft_tokens to get better performance. The eagle_topk and num_draft_tokens should be power of 2 and eagle_topk should be less than 10, num_draft_tokens should be less or equal to 64.

thanks, I will try it asap

2024-10-29 08:59 UTC, yukavio commented
> > @fengyang95 You can pull the new code and run offline_batch_inference.py again. It is my code to create Engine with EAGLE:
> > ```
> > sgl.Engine(model_path="Llama-2-7b-chat-hf", draft_model_path='EAGLE-llama2-chat-7B', disable_cuda_graph=False, 
> >                      num_speculative_steps=2, eagle_topk=2, num_draft_tokens=2,  speculative_algorithm='EAGLE', mem_fraction_static=0.75, 
> >                      dtype='bfloat16')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can change the argument of num_speculative_steps / eagle_topk / num_draft_tokens to get better performance. The eagle_topk and num_draft_tokens should be power of 2 and eagle_topk should be less than 10, num_draft_tokens should be less or equal to 64.
> 
> @yukavio thanks, I will try it asap. Additionally, is fp8 supported? From the code, it seems that FP8 is supported, although I'm uncertain about how to properly quantify the draft model.

I haven't considered quantification yet in my implementation and testing. But I think this shouldn't be a difficult problem to solve. I'm currently busy merging the master branch and resolving conflicts. I may have to look at this issue later. Or you can implement it by yourself if you want😄.
ps. The time-consuming ratio of draft model inference is very low. The benefits of quantifying this may be modest.

2024-10-29 09:04 UTC, fengyang95 commented
> > > @fengyang95 You can pull the new code and run offline_batch_inference.py again. It is my code to create Engine with EAGLE:
> > > ```
> > > sgl.Engine(model_path="Llama-2-7b-chat-hf", draft_model_path='EAGLE-llama2-chat-7B', disable_cuda_graph=False, 
> > >                      num_speculative_steps=2, eagle_topk=2, num_draft_tokens=2,  speculative_algorithm='EAGLE', mem_fraction_static=0.75, 
> > >                      dtype='bfloat16')
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can change the argument of num_speculative_steps / eagle_topk / num_draft_tokens to get better performance. The eagle_topk and num_draft_tokens should be power of 2 and eagle_topk should be less than 10, num_draft_tokens should be less or equal to 64.
> > 
> > 
> > @yukavio thanks, I will try it asap. Additionally, is fp8 supported? From the code, it seems that FP8 is supported, although I'm uncertain about how to properly quantify the draft model.
> 
> I haven't considered quantification yet in my implementation and testing. But I think this shouldn't be a difficult problem to solve. I'm currently busy merging the master branch and resolving conflicts. I may have to look at this issue later. Or you can implement it by yourself if you want😄. ps. The time-consuming ratio of draft model inference is very low. The benefits of quantifying this may be modest.

My target model is quantized, is there a way to keep the draft model in bf16 while the target model remains quantized?

2024-10-29 09:13 UTC, yukavio commented
Currently, it has not been supported.  But I think it is not very difficult
to support it. Personally, I hope to implement these features step by step
after reviewing and merging this PR.  This PR is already too large, making
it difficult to maintain.

Yuanpeng Li ***@***.***> 于2024年10月29日周二 17:05写道：

> @fengyang95 <https://github.com/fengyang95> You can pull the new code and
> run offline_batch_inference.py again. It is my code to create Engine with
> EAGLE:
>
> sgl.Engine(model_path="Llama-2-7b-chat-hf", draft_model_path='EAGLE-llama2-chat-7B', disable_cuda_graph=False,
>                      num_speculative_steps=2, eagle_topk=2, num_draft_tokens=2,  speculative_algorithm='EAGLE', mem_fraction_static=0.75,
>                      dtype='bfloat16')
>
> You can change the argument of num_speculative_steps / eagle_topk /
> num_draft_tokens to get better performance. The eagle_topk and
> num_draft_tokens should be power of 2 and eagle_topk should be less than
> 10, num_draft_tokens should be less or equal to 64.
>
> @yukavio <https://github.com/yukavio> thanks, I will try it asap.
> Additionally, is fp8 supported? From the code, it seems that FP8 is
> supported, although I'm uncertain about how to properly quantify the draft
> model.
>
> I haven't considered quantification yet in my implementation and testing.
> But I think this shouldn't be a difficult problem to solve. I'm currently
> busy merging the master branch and resolving conflicts. I may have to look
> at this issue later. Or you can implement it by yourself if you want😄. ps.
> The time-consuming ratio of draft model inference is very low. The benefits
> of quantifying this may be modest.
>
> My target model is quantized, is there a way to keep the draft model in
> bf16 while the target model remains quantized?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sgl-project/sglang/pull/1498#issuecomment-2443633545>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQELBMJEDVKIQP2TQETTYZDZ55FT7AVCNFSM6AAAAABOXVKUIOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBTGYZTGNJUGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-29 09:14 UTC, yukavio commented
> > > > @fengyang95 You can pull the new code and run offline_batch_inference.py again. It is my code to create Engine with EAGLE:
> > > > ```
> > > > sgl.Engine(model_path="Llama-2-7b-chat-hf", draft_model_path='EAGLE-llama2-chat-7B', disable_cuda_graph=False, 
> > > >                      num_speculative_steps=2, eagle_topk=2, num_draft_tokens=2,  speculative_algorithm='EAGLE', mem_fraction_static=0.75, 
> > > >                      dtype='bfloat16')
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > You can change the argument of num_speculative_steps / eagle_topk / num_draft_tokens to get better performance. The eagle_topk and num_draft_tokens should be power of 2 and eagle_topk should be less than 10, num_draft_tokens should be less or equal to 64.
> > > 
> > > 
> > > @yukavio thanks, I will try it asap. Additionally, is fp8 supported? From the code, it seems that FP8 is supported, although I'm uncertain about how to properly quantify the draft model.
> > 
> > 
> > I haven't considered quantification yet in my implementation and testing. But I think this shouldn't be a difficult problem to solve. I'm currently busy merging the master branch and resolving conflicts. I may have to look at this issue later. Or you can implement it by yourself if you want😄. ps. The time-consuming ratio of draft model inference is very low. The benefits of quantifying this may be modest.
> 
> My target model is quantized, is there a way to keep the draft model in bf16 while the target model remains quantized?

Currently, it has not been supported.  But I think it is not very difficult
to support it. Personally, I hope to implement these features step by step
after reviewing and merging this PR.  This PR is already too large, making
it difficult to maintain.

2024-10-29 11:10 UTC, fengyang95 commented
@yukavio  I conducted tests on DeepSeek-v2 + eagle (which I trained myself, using the llama architecture for the AR layer) with 8 H20 cards.
My draft model can produce normal results using VLLM, indicating that there should be no issues with the model structure.

Here are the errors when using cuda graph:
```bash
 File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
    self.tp_worker = TpModelWorker(
                     ^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
    self.init_cuda_graphs()
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
    self.cuda_graph_runner = CudaGraphRunner(self)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 143, in __init__
    self.model_runner.attn_backend.init_cuda_graph_state(self.max_num_token)
  File "/opt/tiger/sglang/python/sglang/srt/layers/attention/triton_backend.py", line 72, in init_cuda_graph_state
    self.cuda_graph_attn_logits = torch.empty(
                                  ^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 GiB. GPU 1 has a total capacity of 95.00 GiB of which 16.12 GiB is free. Process 1714898 has 78.87 GiB memory in use. Of the allocated memory 76.60 GiB is allocated by PyTorch, and 42.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

When not using cuda graph, the errors are as follows:
```bash
[17:28:42 TP6] Traceback (most recent call last):
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1092, in run_scheduler_process
    scheduler.event_loop()
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 274, in event_loop
    self.run_step()
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 461, in run_step
    result = self.run_batch(new_batch)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 674, in run_batch
    logits_output, next_token_ids = self.draft_worker.forward_batch_speculative_generate(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 69, in forward_batch_speculative_generate
    self.forward_draft_extend(batch)
  File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 44, in forward_draft_extend
    logits_output = self.model_runner.forward(forward_batch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 534, in forward
    return self.forward_extend(forward_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 518, in forward_extend
    return self.model.forward(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 328, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 289, in forward
    torch.cat(
TypeError: expected Tensor as element 1 in argument 0, but got NoneType
```

2024-10-30 02:56 UTC, yukavio commented
> @yukavio I conducted tests on DeepSeek-v2 + eagle (which I trained myself, using the llama architecture for the AR layer) with 8 H20 cards. My draft model can produce normal results using VLLM, indicating that there should be no issues with the model structure.
> 
> Here are the errors when using cuda graph:
> 
> ```shell
>  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
>     self.tp_worker = TpModelWorker(
>                      ^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
>     self.model_runner = ModelRunner(
>                         ^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
>     self.init_cuda_graphs()
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
>     self.cuda_graph_runner = CudaGraphRunner(self)
>                              ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 143, in __init__
>     self.model_runner.attn_backend.init_cuda_graph_state(self.max_num_token)
>   File "/opt/tiger/sglang/python/sglang/srt/layers/attention/triton_backend.py", line 72, in init_cuda_graph_state
>     self.cuda_graph_attn_logits = torch.empty(
>                                   ^^^^^^^^^^^^
> torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 GiB. GPU 1 has a total capacity of 95.00 GiB of which 16.12 GiB is free. Process 1714898 has 78.87 GiB memory in use. Of the allocated memory 76.60 GiB is allocated by PyTorch, and 42.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
> ```
> 
> When not using cuda graph, the errors are as follows:
> 
> ```shell
> [17:28:42 TP6] Traceback (most recent call last):
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1092, in run_scheduler_process
>     scheduler.event_loop()
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 274, in event_loop
>     self.run_step()
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 461, in run_step
>     result = self.run_batch(new_batch)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 674, in run_batch
>     logits_output, next_token_ids = self.draft_worker.forward_batch_speculative_generate(
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 69, in forward_batch_speculative_generate
>     self.forward_draft_extend(batch)
>   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 44, in forward_draft_extend
>     logits_output = self.model_runner.forward(forward_batch)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 534, in forward
>     return self.forward_extend(forward_batch)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 518, in forward_extend
>     return self.model.forward(
>            ^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 328, in forward
>     hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 289, in forward
>     torch.cat(
> TypeError: expected Tensor as element 1 in argument 0, but got NoneType
> ```

For the first case, you should try to use flash-infer as attention backend to fix it.

For the last case, It sames your target model is failed to capture the hidden states. You can add code like to your target model (DeepSeek-V2 or other) like: https://github.com/sgl-project/sglang/pull/1498/files#diff-f6f7943965e41f2d4081018071c87bc1e9f806d5d639579688eb5f6c02f250cdR320.
I will refine this implementation later to avoid the edit of model implementation.

2024-10-30 03:21 UTC, coolhok commented
I am using the latest code for offline testing。
At the beginning of the cycle，tps = 180 tokens/s，
But after a few cycles, there will be a serious decrease in speed，tps 180 tokens/s -> 57 tokens/s -> 38 tokens/s

```
import sglang as sgl
import time
import json

def main():
    # Sample prompts.
    prompts = [
        # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: Where is the capital city of France? ASSISTANT:",
        "[INST] <<SYS>>\\nYou are a helpful assistant.\\n<</SYS>>\\n如何赚取 10000w？ [/INST]"
        # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: 你是谁呢？ ASSISTANT:"
    ]
    # Create a sampling params object.
    sampling_params = {"temperature": 0, "max_new_tokens": 256,}


    draft_model_path = "/mnt/data/model_hub/EAGLE-llama2-chat-7B"
    model_path = "/mnt/data/model_hub/Llama-2-7b-chat-hf"
    # Create an LLM.
    llm = sgl.Engine(model_path=model_path, draft_model_path=draft_model_path, disable_cuda_graph=False, num_speculative_steps=4, eagle_topk=4, num_draft_tokens=32, speculative_algorithm='EAGLE', mem_fraction_static=0.60)
    # llm = sgl.Engine(model_path=model_path, disable_cuda_graph=False, mem_fraction_static=0.60)
    #outputs = llm.generate(prompts, sampling_params)

    for _ in range(100):
        start = time.time()
        outputs = llm.generate(prompts, sampling_params)
        cos = time.time()-start
        # print(f"!!!! {json.dumps(outputs)}")
        completion_tokens = outputs[0]["meta_info"]["completion_tokens"]
        # Print the outputs.
        for prompt, output in zip(prompts, outputs):
            print(f"!!!!!!!!! tps =: {completion_tokens/cos}")

# The __main__ condition is necessary here because we use "spawn" to create subprocesses
# Spawn starts a fresh program every time, if there is no __main__, it will run into infinite loop to keep spawning processes from sgl.Engine
if __name__ == "__main__":
    main()
```

2024-10-30 08:55 UTC, yukavio commented
> I am using the latest code for offline testing。 At the beginning of the cycle，tps = 180 tokens/s， But after a few cycles, there will be a serious decrease in speed，tps 180 tokens/s -> 57 tokens/s -> 38 tokens/s
> 
> ```
> import sglang as sgl
> import time
> import json
> 
> def main():
>     # Sample prompts.
>     prompts = [
>         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: Where is the capital city of France? ASSISTANT:",
>         "[INST] <<SYS>>\\nYou are a helpful assistant.\\n<</SYS>>\\n如何赚取 10000w？ [/INST]"
>         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: 你是谁呢？ ASSISTANT:"
>     ]
>     # Create a sampling params object.
>     sampling_params = {"temperature": 0, "max_new_tokens": 256,}
> 
> 
>     draft_model_path = "/mnt/data/model_hub/EAGLE-llama2-chat-7B"
>     model_path = "/mnt/data/model_hub/Llama-2-7b-chat-hf"
>     # Create an LLM.
>     llm = sgl.Engine(model_path=model_path, draft_model_path=draft_model_path, disable_cuda_graph=False, num_speculative_steps=4, eagle_topk=4, num_draft_tokens=32, speculative_algorithm='EAGLE', mem_fraction_static=0.60)
>     # llm = sgl.Engine(model_path=model_path, disable_cuda_graph=False, mem_fraction_static=0.60)
>     #outputs = llm.generate(prompts, sampling_params)
> 
>     for _ in range(100):
>         start = time.time()
>         outputs = llm.generate(prompts, sampling_params)
>         cos = time.time()-start
>         # print(f"!!!! {json.dumps(outputs)}")
>         completion_tokens = outputs[0]["meta_info"]["completion_tokens"]
>         # Print the outputs.
>         for prompt, output in zip(prompts, outputs):
>             print(f"!!!!!!!!! tps =: {completion_tokens/cos}")
> 
> # The __main__ condition is necessary here because we use "spawn" to create subprocesses
> # Spawn starts a fresh program every time, if there is no __main__, it will run into infinite loop to keep spawning processes from sgl.Engine
> if __name__ == "__main__":
>     main()
> ```

Thanks for the report. I will check and fix it later.

2024-10-30 11:56 UTC, fengyang95 commented
> > @yukavio I conducted tests on DeepSeek-v2 + eagle (which I trained myself, using the llama architecture for the AR layer) with 8 H20 cards. My draft model can produce normal results using VLLM, indicating that there should be no issues with the model structure.
> > Here are the errors when using cuda graph:
> > ```shell
> >  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
> >     self.tp_worker = TpModelWorker(
> >                      ^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
> >     self.model_runner = ModelRunner(
> >                         ^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
> >     self.init_cuda_graphs()
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
> >     self.cuda_graph_runner = CudaGraphRunner(self)
> >                              ^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 143, in __init__
> >     self.model_runner.attn_backend.init_cuda_graph_state(self.max_num_token)
> >   File "/opt/tiger/sglang/python/sglang/srt/layers/attention/triton_backend.py", line 72, in init_cuda_graph_state
> >     self.cuda_graph_attn_logits = torch.empty(
> >                                   ^^^^^^^^^^^^
> > torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 GiB. GPU 1 has a total capacity of 95.00 GiB of which 16.12 GiB is free. Process 1714898 has 78.87 GiB memory in use. Of the allocated memory 76.60 GiB is allocated by PyTorch, and 42.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When not using cuda graph, the errors are as follows:
> > ```shell
> > [17:28:42 TP6] Traceback (most recent call last):
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1092, in run_scheduler_process
> >     scheduler.event_loop()
> >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> >     return func(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 274, in event_loop
> >     self.run_step()
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 461, in run_step
> >     result = self.run_batch(new_batch)
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 674, in run_batch
> >     logits_output, next_token_ids = self.draft_worker.forward_batch_speculative_generate(
> >                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 69, in forward_batch_speculative_generate
> >     self.forward_draft_extend(batch)
> >   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 44, in forward_draft_extend
> >     logits_output = self.model_runner.forward(forward_batch)
> >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 534, in forward
> >     return self.forward_extend(forward_batch)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 518, in forward_extend
> >     return self.model.forward(
> >            ^^^^^^^^^^^^^^^^^^^
> >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> >     return func(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 328, in forward
> >     hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
> >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
> >     return self._call_impl(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
> >     return forward_call(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 289, in forward
> >     torch.cat(
> > TypeError: expected Tensor as element 1 in argument 0, but got NoneType
> > ```
> 
> For the first case, you should try to use flash-infer as attention backend to fix it.
> 
> For the last case, It sames your target model is failed to capture the hidden states. You can add code like to your target model (DeepSeek-V2 or other) like: https://github.com/sgl-project/sglang/pull/1498/files#diff-f6f7943965e41f2d4081018071c87bc1e9f806d5d639579688eb5f6c02f250cdR320. I will refine this implementation later to avoid the editing of model implementation.

@yukavio got another issue:
```bash
[19:16:21 TP5] Traceback (most recent call last):
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1090, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
    self.tp_worker = TpModelWorker(
                     ^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
    self.init_cuda_graphs()
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
    self.cuda_graph_runner = CudaGraphRunner(self)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 167, in __init__
    self.capture()
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 196, in capture
    ) = self.capture_one_batch_size(bs, num_token, forward)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 255, in capture_one_batch_size
    run_once(self.capture_forward_mode)
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 249, in run_once
    return forward(input_ids, forward_batch.positions, forward_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sglang/python/sglang/srt/models/deepseek_v2.py", line 662, in forward
    hidden_states = self.model(input_ids, positions, forward_batch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line  [...]

2024-10-31 08:56 UTC, yukavio commented
FYI. Due to the large number of modifications to the attention backend part of the main branch. I need some time to fix the conflicts caused by code migration.

2024-11-05 10:26 UTC, yukavio commented
> I am using the latest code for offline testing。 At the beginning of the cycle，tps = 180 tokens/s， But after a few cycles, there will be a serious decrease in speed，tps 180 tokens/s -> 57 tokens/s -> 38 tokens/s
> 
> ```
> import sglang as sgl
> import time
> import json
> 
> def main():
>     # Sample prompts.
>     prompts = [
>         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: Where is the capital city of France? ASSISTANT:",
>         "[INST] <<SYS>>\\nYou are a helpful assistant.\\n<</SYS>>\\n如何赚取 10000w？ [/INST]"
>         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: 你是谁呢？ ASSISTANT:"
>     ]
>     # Create a sampling params object.
>     sampling_params = {"temperature": 0, "max_new_tokens": 256,}
> 
> 
>     draft_model_path = "/mnt/data/model_hub/EAGLE-llama2-chat-7B"
>     model_path = "/mnt/data/model_hub/Llama-2-7b-chat-hf"
>     # Create an LLM.
>     llm = sgl.Engine(model_path=model_path, draft_model_path=draft_model_path, disable_cuda_graph=False, num_speculative_steps=4, eagle_topk=4, num_draft_tokens=32, speculative_algorithm='EAGLE', mem_fraction_static=0.60)
>     # llm = sgl.Engine(model_path=model_path, disable_cuda_graph=False, mem_fraction_static=0.60)
>     #outputs = llm.generate(prompts, sampling_params)
> 
>     for _ in range(100):
>         start = time.time()
>         outputs = llm.generate(prompts, sampling_params)
>         cos = time.time()-start
>         # print(f"!!!! {json.dumps(outputs)}")
>         completion_tokens = outputs[0]["meta_info"]["completion_tokens"]
>         # Print the outputs.
>         for prompt, output in zip(prompts, outputs):
>             print(f"!!!!!!!!! tps =: {completion_tokens/cos}")
> 
> # The __main__ condition is necessary here because we use "spawn" to create subprocesses
> # Spawn starts a fresh program every time, if there is no __main__, it will run into infinite loop to keep spawning processes from sgl.Engine
> if __name__ == "__main__":
>     main()
> ```

I have fixed it. You can update the code and rerun it.

2024-11-05 10:42 UTC, yukavio commented
> > > @yukavio I conducted tests on DeepSeek-v2 + eagle (which I trained myself, using the llama architecture for the AR layer) with 8 H20 cards. My draft model can produce normal results using VLLM, indicating that there should be no issues with the model structure.
> > > Here are the errors when using cuda graph:
> > > ```shell
> > >  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
> > >     self.tp_worker = TpModelWorker(
> > >                      ^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
> > >     self.model_runner = ModelRunner(
> > >                         ^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
> > >     self.init_cuda_graphs()
> > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
> > >     self.cuda_graph_runner = CudaGraphRunner(self)
> > >                              ^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 143, in __init__
> > >     self.model_runner.attn_backend.init_cuda_graph_state(self.max_num_token)
> > >   File "/opt/tiger/sglang/python/sglang/srt/layers/attention/triton_backend.py", line 72, in init_cuda_graph_state
> > >     self.cuda_graph_attn_logits = torch.empty(
> > >                                   ^^^^^^^^^^^^
> > > torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 GiB. GPU 1 has a total capacity of 95.00 GiB of which 16.12 GiB is free. Process 1714898 has 78.87 GiB memory in use. Of the allocated memory 76.60 GiB is allocated by PyTorch, and 42.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > When not using cuda graph, the errors are as follows:
> > > ```shell
> > > [17:28:42 TP6] Traceback (most recent call last):
> > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1092, in run_scheduler_process
> > >     scheduler.event_loop()
> > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> > >     return func(*args, **kwargs)
> > >            ^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 274, in event_loop
> > >     self.run_step()
> > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 461, in run_step
> > >     result = self.run_batch(new_batch)
> > >              ^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 674, in run_batch
> > >     logits_output, next_token_ids = self.draft_worker.forward_batch_speculative_generate(
> > >                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 69, in forward_batch_speculative_generate
> > >     self.forward_draft_extend(batch)
> > >   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 44, in forward_draft_extend
> > >     logits_output = self.model_runner.forward(forward_batch)
> > >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 534, in forward
> > >     return self.forward_extend(forward_batch)
> > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 518, in forward_extend
> > >     return self.model.forward(
> > >            ^^^^^^^^^^^^^^^^^^^
> > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> > >     return func(*args, **kwargs)
> > >            ^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 328, in forward
> > >     hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
> > >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
> > >     return self._call_impl(*args, **kwargs)
> > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 289, in forward
> > >     torch.cat(
> > > TypeError: expected Tensor as element 1 in argument 0, but got NoneType
> > > ```
> > 
> > 
> > For the first case, you should try to use flash-infer as attention backend to fix it.
> > For the last case, It sames your target model is failed to capture the hidden states. You can add code like to your target model (DeepSeek-V2 or other) like: https://github.com/sgl-project/sglang/pull/1498/files#diff-f6f7943965e41f2d4081018071c87bc1e9f806d5d639579688eb5f6c02f250cdR320. I will refine this implementation later to avoid the editing of model implementation.
> 
> @yukavio got another issue:
> 
> ```shell
> [19:16:21 TP5] Traceback (most recent call last):
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1090, in run_scheduler_process
>     scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
>     self.tp_worker = TpModelWorker(
>                      ^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
>     self.model_runner = ModelRunner(
>                         ^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
>     self.init_cuda_graphs()
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
>     self.cuda_graph_runner = CudaGraphRunner(self)
>                              ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 167, in __init__
>     self.capture()
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 196, in capture
>     ) = self.capture_one_batch_size(bs, num_token, forward)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 255, in capture_one_batch_size
>     run_once(self.capture_forward_mode)
>   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 249, in run_once
>     return forward(input_ids, forward_batch.positions, forward_batch)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/tiger/sglang/python/sglang/srt/models/deepseek_v2.py", line 662, in forward
>     hidden_states = self.model(input_ids, positions, forward_batch)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module. [...]

2024-11-05 11:29 UTC, yukavio commented
> @yukavio Hi yukavio Recently, SGLang has undergone some refactoring work. You need to merge the latest main to resolve the corresponding conflicts. Thanks!

I have 

<img width="803" alt="image" src="https://github.com/user-attachments/assets/4b6f87ed-76ad-4d2c-8a9a-028aa2795afe">


> @yukavio Hi yukavio Recently, SGLang has undergone some refactoring work. You need to merge the latest main to resolve the corresponding conflicts. Thanks!



> @yukavio Hi yukavio Recently, SGLang has undergone some refactoring work. You need to merge the latest main to resolve the corresponding conflicts. Thanks!

I have merged the main branch and fixed the corresponding conflicts. Do you know if I need to add a corresponding unit test? If necessary, EAGLE's tests need to rely on the specific model. Please tell me how to add dependent models.

2024-11-06 02:45 UTC, coolhok commented
> > I am using the latest code for offline testing。 At the beginning of the cycle，tps = 180 tokens/s， But after a few cycles, there will be a serious decrease in speed，tps 180 tokens/s -> 57 tokens/s -> 38 tokens/s
> > ```
> > import sglang as sgl
> > import time
> > import json
> > 
> > def main():
> >     # Sample prompts.
> >     prompts = [
> >         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: Where is the capital city of France? ASSISTANT:",
> >         "[INST] <<SYS>>\\nYou are a helpful assistant.\\n<</SYS>>\\n如何赚取 10000w？ [/INST]"
> >         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: 你是谁呢？ ASSISTANT:"
> >     ]
> >     # Create a sampling params object.
> >     sampling_params = {"temperature": 0, "max_new_tokens": 256,}
> > 
> > 
> >     draft_model_path = "/mnt/data/model_hub/EAGLE-llama2-chat-7B"
> >     model_path = "/mnt/data/model_hub/Llama-2-7b-chat-hf"
> >     # Create an LLM.
> >     llm = sgl.Engine(model_path=model_path, draft_model_path=draft_model_path, disable_cuda_graph=False, num_speculative_steps=4, eagle_topk=4, num_draft_tokens=32, speculative_algorithm='EAGLE', mem_fraction_static=0.60)
> >     # llm = sgl.Engine(model_path=model_path, disable_cuda_graph=False, mem_fraction_static=0.60)
> >     #outputs = llm.generate(prompts, sampling_params)
> > 
> >     for _ in range(100):
> >         start = time.time()
> >         outputs = llm.generate(prompts, sampling_params)
> >         cos = time.time()-start
> >         # print(f"!!!! {json.dumps(outputs)}")
> >         completion_tokens = outputs[0]["meta_info"]["completion_tokens"]
> >         # Print the outputs.
> >         for prompt, output in zip(prompts, outputs):
> >             print(f"!!!!!!!!! tps =: {completion_tokens/cos}")
> > 
> > # The __main__ condition is necessary here because we use "spawn" to create subprocesses
> > # Spawn starts a fresh program every time, if there is no __main__, it will run into infinite loop to keep spawning processes from sgl.Engine
> > if __name__ == "__main__":
> >     main()
> > ```
> 
> Thanks for the report. I will check and fix it later.

if set disable_radix_cache= True,The speed of 1000 cycles is very stable!

2024-11-06 09:50 UTC, bisunny commented
one issue is EAGLE cannot support the use of certain sampling parameters, such as repetition_penalty.

2024-11-06 10:15 UTC, yukavio commented
> > > I am using the latest code for offline testing。 At the beginning of the cycle，tps = 180 tokens/s， But after a few cycles, there will be a serious decrease in speed，tps 180 tokens/s -> 57 tokens/s -> 38 tokens/s
> > > ```
> > > import sglang as sgl
> > > import time
> > > import json
> > > 
> > > def main():
> > >     # Sample prompts.
> > >     prompts = [
> > >         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: Where is the capital city of France? ASSISTANT:",
> > >         "[INST] <<SYS>>\\nYou are a helpful assistant.\\n<</SYS>>\\n如何赚取 10000w？ [/INST]"
> > >         # "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: 你是谁呢？ ASSISTANT:"
> > >     ]
> > >     # Create a sampling params object.
> > >     sampling_params = {"temperature": 0, "max_new_tokens": 256,}
> > > 
> > > 
> > >     draft_model_path = "/mnt/data/model_hub/EAGLE-llama2-chat-7B"
> > >     model_path = "/mnt/data/model_hub/Llama-2-7b-chat-hf"
> > >     # Create an LLM.
> > >     llm = sgl.Engine(model_path=model_path, draft_model_path=draft_model_path, disable_cuda_graph=False, num_speculative_steps=4, eagle_topk=4, num_draft_tokens=32, speculative_algorithm='EAGLE', mem_fraction_static=0.60)
> > >     # llm = sgl.Engine(model_path=model_path, disable_cuda_graph=False, mem_fraction_static=0.60)
> > >     #outputs = llm.generate(prompts, sampling_params)
> > > 
> > >     for _ in range(100):
> > >         start = time.time()
> > >         outputs = llm.generate(prompts, sampling_params)
> > >         cos = time.time()-start
> > >         # print(f"!!!! {json.dumps(outputs)}")
> > >         completion_tokens = outputs[0]["meta_info"]["completion_tokens"]
> > >         # Print the outputs.
> > >         for prompt, output in zip(prompts, outputs):
> > >             print(f"!!!!!!!!! tps =: {completion_tokens/cos}")
> > > 
> > > # The __main__ condition is necessary here because we use "spawn" to create subprocesses
> > > # Spawn starts a fresh program every time, if there is no __main__, it will run into infinite loop to keep spawning processes from sgl.Engine
> > > if __name__ == "__main__":
> > >     main()
> > > ```
> > 
> > 
> > Thanks for the report. I will check and fix it later.
> 
> if set disable_radix_cache= True,The speed of 1000 cycles is very stable!

It is due to the draft model not supporting prefix share now. I am trying to support it.

2024-11-06 10:16 UTC, yukavio commented
> one issue is EAGLE cannot support the use of certain sampling parameters, such as repetition_penalty.
Yes, but I personally have no plans to implement this feature in this PR at this time.

2024-11-06 11:33 UTC, fengyang95 commented
> > > > @yukavio I conducted tests on DeepSeek-v2 + eagle (which I trained myself, using the llama architecture for the AR layer) with 8 H20 cards. My draft model can produce normal results using VLLM, indicating that there should be no issues with the model structure.
> > > > Here are the errors when using cuda graph:
> > > > ```shell
> > > >  File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
> > > >     self.tp_worker = TpModelWorker(
> > > >                      ^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
> > > >     self.model_runner = ModelRunner(
> > > >                         ^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
> > > >     self.init_cuda_graphs()
> > > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
> > > >     self.cuda_graph_runner = CudaGraphRunner(self)
> > > >                              ^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 143, in __init__
> > > >     self.model_runner.attn_backend.init_cuda_graph_state(self.max_num_token)
> > > >   File "/opt/tiger/sglang/python/sglang/srt/layers/attention/triton_backend.py", line 72, in init_cuda_graph_state
> > > >     self.cuda_graph_attn_logits = torch.empty(
> > > >                                   ^^^^^^^^^^^^
> > > > torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 GiB. GPU 1 has a total capacity of 95.00 GiB of which 16.12 GiB is free. Process 1714898 has 78.87 GiB memory in use. Of the allocated memory 76.60 GiB is allocated by PyTorch, and 42.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > When not using cuda graph, the errors are as follows:
> > > > ```shell
> > > > [17:28:42 TP6] Traceback (most recent call last):
> > > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1092, in run_scheduler_process
> > > >     scheduler.event_loop()
> > > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> > > >     return func(*args, **kwargs)
> > > >            ^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 274, in event_loop
> > > >     self.run_step()
> > > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 461, in run_step
> > > >     result = self.run_batch(new_batch)
> > > >              ^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 674, in run_batch
> > > >     logits_output, next_token_ids = self.draft_worker.forward_batch_speculative_generate(
> > > >                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 69, in forward_batch_speculative_generate
> > > >     self.forward_draft_extend(batch)
> > > >   File "/opt/tiger/sglang/python/sglang/srt/speculative/eagle_worker.py", line 44, in forward_draft_extend
> > > >     logits_output = self.model_runner.forward(forward_batch)
> > > >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 534, in forward
> > > >     return self.forward_extend(forward_batch)
> > > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 518, in forward_extend
> > > >     return self.model.forward(
> > > >            ^^^^^^^^^^^^^^^^^^^
> > > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> > > >     return func(*args, **kwargs)
> > > >            ^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 328, in forward
> > > >     hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
> > > >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
> > > >     return self._call_impl(*args, **kwargs)
> > > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
> > > >     return forward_call(*args, **kwargs)
> > > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   File "/opt/tiger/sglang/python/sglang/srt/models/llama_eagle.py", line 289, in forward
> > > >     torch.cat(
> > > > TypeError: expected Tensor as element 1 in argument 0, but got NoneType
> > > > ```
> > > 
> > > 
> > > For the first case, you should try to use flash-infer as attention backend to fix it.
> > > For the last case, It sames your target model is failed to capture the hidden states. You can add code like to your target model (DeepSeek-V2 or other) like: https://github.com/sgl-project/sglang/pull/1498/files#diff-f6f7943965e41f2d4081018071c87bc1e9f806d5d639579688eb5f6c02f250cdR320. I will refine this implementation later to avoid the editing of model implementation.
> > 
> > 
> > @yukavio got another issue:
> > ```shell
> > [19:16:21 TP5] Traceback (most recent call last):
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 1090, in run_scheduler_process
> >     scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank)
> >                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/scheduler.py", line 143, in __init__
> >     self.tp_worker = TpModelWorker(
> >                      ^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 62, in __init__
> >     self.model_runner = ModelRunner(
> >                         ^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 141, in __init__
> >     self.init_cuda_graphs()
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 504, in init_cuda_graphs
> >     self.cuda_graph_runner = CudaGraphRunner(self)
> >                              ^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 167, in __init__
> >     self.capture()
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 196, in capture
> >     ) = self.capture_one_batch_size(bs, num_token, forward)
> >         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 255, in capture_one_batch_size
> >     run_once(self.capture_forward_mode)
> >   File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 249, in run_once
> >     return forward(input_ids, forward_batch.positions, forward_batch)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> >     return func(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^
> >   File "/opt/tiger/sglang/python/sglang/srt/models/deepseek_v2.py", line 662, in forward
> >     hidden [...]

2024-11-14 11:06 UTC, yukavio commented
Add a memo: cutex should be added to dependency list of Sglang after review.

2024-11-17 02:27 UTC, merrymercy commented
@yukavio Can you resolve the conflicts?

2024-11-18 03:27 UTC, yukavio commented
> @yukavio Can you resolve the conflicts?

Fixed. Could you please help me to trigger the CI?

2024-11-18 09:04 UTC, yukavio commented
CI has failed due to timeout.

2024-11-22 01:06 UTC, merrymercy requested changes
I did an initial code style review. I will follow up with a more careful logic review. We want to merge this soon.

Some guidelines:
1. Split the big PR into smaller PRs. Merge small unreachable code first. (e.g., introduce two forward modes).
2. Minimize the code change of the common scheduler and move most things into self-contained eagle-specific files

Sorry for the frequent changes on the main branch. We did a lot of refactoring to enable the overlap scheduler by default. That refactor has been finished (https://github.com/sgl-project/sglang/commit/7d671e4ad2977d8090f44be5e94f351a15f4c9bf) so we do not expect big changes after that. This PR is now our top priority.

2024-11-22 01:06 UTC, merrymercy commented on examples/runtime/engine/EAGLE_offline_batch_inference.py
> +        mem_fraction_static=0.65,
We can set most of these (e.g., `disable_radix_cache`) in `server_args.py` automatically when the users set `speculative_algorithm="EAGLE"`, so users do not need to worry about these arguments.
See examples here https://github.com/sgl-project/sglang/blob/f35cb46cc37661d772db5964653c906dac41edbe/python/sglang/srt/server_args.py#L187-L188

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch: ForwardBatch = None,
1. What is `num_token`?
2. Can we explicitly list all required arguments instead of passing `ForwardBatch`?

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +from sglang.srt.model_executor.forward_batch_info import ForwardBatch, ForwardMode
It seems the modifications of this file are for two functions:
- Support ForwardMode.SPEC_EXTEND
- Support ForwardMode.SPEC_VERIFY with cuda graph

Am I correct?

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_utils.py
> +from enum import Enum, auto
This file is not necessary anymore. Can you move all functions under `flashinfer_backend.py`?

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/layers/logits_processor.py
> +    # Used by speculative inference
```suggestion
    # Used by speculative inference (eagle)
```

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/layers/logits_processor.py
> +            capture_hidden_mode=getattr(
try to get rid of `getattr`

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/layers/logits_processor.py
> +        if forward_batch.forward_mode.is_extend() and hasattr(
This seems redundant. Merge this with the if/else above (L80)

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/layers/logits_processor.py
> +                next_token_logits_bak=last_logits,
Can we do the backup somewhere else? It seems pretty redundant that you return the same value twice.

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/managers/schedule_batch.py
> +    spec_algorithm: str = None
`spec_algorithm` can goto `SpecInput` or somewhere else.

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/managers/scheduler.py
> +                        self.draft_worker.forward_batch_speculative_generate(batch)
Can we make `self.tp_worker.forward_batch_generation` accept the same arguments as `self.tp_worker.forward_batch_generation`

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/managers/tp_worker.py
> +        is_draft_worker = getattr(self, "is_draft_worker", False)
Do not use `getattr` to work around compatibility issues. Let us make sure every filed is set correctly for all code paths.

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/managers/tp_worker.py
> +        self, model_worker_batch: ModelWorkerBatch, need_token_id=True
style: rename `need_token_id` to `skip_sample`

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/model_executor/cuda_graph_runner.py
> +        if model_runner.server_args.speculative_algorithm == "EAGLE":
style: create an ENUM for spec algorithms instead of using string.

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/model_executor/forward_batch_info.py
> +    SPECEXTEND = auto()
style: `SPECVERIFY` -> `SPEC_VERIFY`, `SPECEXTEND` -> `SPEC_EXTEND`

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/model_executor/forward_batch_info.py
> +    def is_verify(self):
```suggestion
    def is_spec_verify(self):
```

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/model_executor/model_runner.py
> +            and forward_batch.forward_mode.is_cuda_graph()
move the check `and forward_batch.forward_mode.is_cuda_graph()` into `self.cuda_graph_runner.can_run(forward_batch)`

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/server_args.py
> +    draft_model_path: str = None
style:
```suggestion
    draft_model_path: Optional[str] = None
```

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/server_args.py
> +            type=List[str],
I do not think `type=List[str]` can work with argparse.

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/models/llama_eagle.py
> +class LlamaMLP(nn.Module):
import the command parts from llama.py

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/speculative/build_eagle_tree.py
> +__global__ void build_tree(Tensor<long, 2> parent_list, Tensor<long, 2> selected_index, Tensor<int, 1> verified_seq_len,
is it possible to do this with triton?

2024-11-22 01:06 UTC, merrymercy commented on python/sglang/srt/speculative/eagle_utils.py
> +from .build_eagle_tree import build_tree_kernel
use absolute path

2024-11-22 08:00 UTC, yukavio commented on examples/runtime/engine/EAGLE_offline_batch_inference.py
> +        mem_fraction_static=0.65,
OK, I will solve it in new PR.

2024-11-22 08:02 UTC, yukavio commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch: ForwardBatch = None,
In speculative deocding, batch_size is not always equal to the number of model input, so we should use an argument to specify it.

2024-11-22 08:05 UTC, yukavio commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +from sglang.srt.model_executor.forward_batch_info import ForwardBatch, ForwardMode
Yes

2024-11-22 08:06 UTC, yukavio commented on python/sglang/srt/layers/attention/flashinfer_utils.py
> +from enum import Enum, auto
Sorry, I missed it when merging the code. I will remove it later.

2024-11-22 09:37 UTC, jjjjohnson commented on python/sglang/srt/model_executor/cuda_graph_runner.py
> +        self.positions[:raw_num_token].copy_(positions)
@yukavio Do we need to assign spec_info.custom_mask to self.cuda_graph_custom_mask before replay?

2024-11-23 03:15 UTC, merrymercy requested changes

2024-11-23 03:15 UTC, merrymercy commented on python/sglang/srt/speculative/eagle_utils.py
> +        ]
```suggestion
        self.next_token_logits_back = next_token_logits_back
        logits_output.next_token_logits = logits_output.next_token_logits[
            accept_index
        ]
```

2024-11-24 02:22 UTC, closed without merging

2024-11-24 02:41 UTC, merrymercy requested changes

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch: ForwardBatch = None,
Style. If one argument can be None, we should use "Optional[xx] instead of xxx"

```suggestion
        encoder_lens: Optional[torch.Tensor] = None,
        spec_info: Optional["SpecInput"] = None,
        is_draft_runner: bool = False,
        forward_batch: Optional[ForwardBatch] = None,
```

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch=None,
correct the type annotation, use `Optional`

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +                forward_batch=forward_batch,
I do not think we need this for `indices_updater_decode

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +            (max_bs * (self.max_context_len + 7) // 8),
why is a rounding needed here?

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +        if spec_info is not None and not is_draft_runner:
we can use forward_mode.is_target_verify() as a condition.

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +        is_draft_runner: bool = False,
`is_draft_runner` seems not useful.

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +                decode_wrappers.append(
call it prefill_wrappers

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +        forward_batch=None,
keep type annotations.

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/layers/logits_processor.py
> +    next_token_logits_bak: Optional[torch.Tensor] = None
we do not need this.

2024-11-24 02:41 UTC, merrymercy commented on python/sglang/srt/managers/data_parallel_controller.py
> +                sockets.append(bind_port(tmp_port_args.nccl_port[0]))
use another variable instead of making it a list.