Add support for Molmo-D-7B Model
sgl-project/sglang pull request #1542
Opened 2024-09-30 08:45 UTC by BabyChouSr

Support for https://huggingface.co/allenai/Molmo-7B-D-0924

It's been awhile since I've supported a model, so I figured it would be good practice. It seems to be a CLIP-Vit encoder with some embedding pooling and then a Qwen LLM backbone. I'm trying to figure out the vision backbone first and then I think the frozen parts will come together by importing from Qwen2.py file.

2024-10-05 16:54 UTC, jlia0 commented
Any updates on this?

2024-10-05 19:22 UTC, BabyChouSr commented
@jlia0 I'm working on this slowly since I'm juggling a couple things. It will take me probably a week.

2024-10-09 06:49 UTC, BabyChouSr commented
/ready

2024-10-11 11:01 UTC, merrymercy requested changes

2024-10-11 11:01 UTC, merrymercy commented on test/srt/models/test_molmo.py
> +                self.assert_srt_vision_backbone_and_hf_vision_backbone_close(
Do you have an end-to-end test for the whole model?
Can you add a new test here https://github.com/sgl-project/sglang/blob/main/test/srt/test_vision_openai_server.py?

2024-11-08 08:33 UTC, merrymercy commented
Closed due to inactivity. Feel free to reopen if you have new progress.

2024-11-08 08:33 UTC, closed without merging