docs: add zh_CN po files
sgl-project/sglang pull request #1660
Opened 2024-10-14 01:05 UTC by llama-factory

## Motivation

contribute Chinese documentation

## Modifications

add Chinese po files

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

#1565

2024-10-14 03:38 UTC, merrymercy commented
Thanks for the contribution.

Can you provide the scripts to generate these files? So that we can regenerate them next time if we update the docs.

2024-10-14 05:09 UTC, llama-factory commented
> Thanks for the contribution.
> 
> Can you provide the scripts to generate these files? So that we can regenerate them next time if we update the docs.

ok, 
source code: https://github.com/llama-factory/llamafactory/blob/main/code/sphinx_translate.py
prompt in this [blog](https://blog.csdn.net/budahui/article/details/142748857?spm=1001.2014.3001.5502)

2024-10-14 05:40 UTC, merrymercy approved these changes
LGTM.  @zhyncs please take another review and we can probably merge it.

2024-10-14 05:42 UTC, zhyncs commented on docs/locale/zh_CN/LC_MESSAGES/choices_methods.po
> +"LLM 调用来获取无条件似然。"
This translation is too stiff.🥲

2024-10-17 04:16 UTC, zhyncs requested changes
@llama-factory First of all, thanks for your work! I went through this document as a whole and found that the translation of Gemini 1.5 Flash is rather inaccurate, and it seems not to have understood some technical terms in the original text. Can you manually revise it or try other APIs like GPT-4o?

2024-10-17 04:57 UTC, llama-factory commented
> @llama-factory First of all, thanks for your work! I went through this document as a whole and found that the translation of Gemini 1.5 Flash is rather inaccurate, and it seems not to have understood some technical terms in the original text. Can you manually revise it or try other APIs like GPT-4o?

we currently don’t have the budget to call better models like GPT-4 or Claude 3.5. The source code and usage instructions have already been provided earlier. If you find it valuable, feel free to use it and test the performance on more advanced models.

2024-10-17 17:11 UTC, zhyncs commented
> > @llama-factory First of all, thanks for your work! I went through this document as a whole and found that the translation of Gemini 1.5 Flash is rather inaccurate, and it seems not to have understood some technical terms in the original text. Can you manually revise it or try other APIs like GPT-4o?
> 
> we currently don’t have the budget to call better models like GPT-4 or Claude 3.5. The source code and usage instructions have already been provided earlier. If you find it valuable, feel free to use it and test the performance on more advanced models.

Ok Thanks! @zhaochenyang20 May you try this?

2024-10-17 17:11 UTC, closed without merging