Debug studio
sgl-project/sglang pull request #1831
Opened 2024-10-29 07:04 UTC by zolinthecow

## Motivation

When developing apps (especially more complex ones) with SGLang's frontend it's a bit hard to tell what is actually getting passed into the `generate/` endpoint. This PR introduces a "prompt debugging studio" that allows you to turn on a debug mode and will start intercepting generate requests and saving them to a debug server, where you can go to a web interface and view all the prompts and responses for SGL functions.

For example, if you start the debug server:

```bash
python -m sglang.launch_debug_server
```

It will start a debug server on `http://0.0.0.0:56765`

Then, you can add a debug region to an sgl function:

```python
@sgl.function
def text_qa(s, question):
    s.begin_debug_region("TEXT_QA")
    s += "Q: " + question + "\n"
    s += "A:" + sgl.gen("answer", stop="\n")

state = text_qa.run(
    question="What is the capital of France?",
    temperature=0.1,
    stream=True
)
```

The `s.begin_debug_region` will start debugging under the prompt name "TEXT_QA". You can then go to `http://localhost:56765` (will have to ssh forward if you're developing on a remote server) and you should see prompts start appearing

![image](https://github.com/user-attachments/assets/b1941fbb-e089-45d3-9a9d-3a0da30d8174)

## Modifications

- Adds BeginDebugRegion and EndDebugRegion to SGLExpr for the frontend language
- Adds `launch_debug_server` which under the hood relies on `enochian-studio` (one of my packages) for the debug server
  - `enochian-studio` can be found [here](https://github.com/zolinthecow/enochian-js/tree/master/studio), I can say it's up to date since I maintain it, along with Etched
- Adds posting to the debug server if enabled for all backends

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

2024-10-30 03:53 UTC, zolinthecow commented
^ Couldn't reproduce CI error locally :(

2024-11-01 18:12 UTC, zhaochenyang20 commented
@zolinthecow Nice work! I will start to review this PR this weekend. Stay tuned!

2024-11-09 23:32 UTC, merrymercy requested changes
Overall, it looks good! I left a few minor comments.
One thing we want to ensure is that it does not introduce any overhead when debug mode is turned off (e.g., use as few function calls and if statements as possible at runtime).

2024-11-09 23:32 UTC, merrymercy commented on docs/frontend/frontend.md
> +python -m sglang.launch_debug_server
```suggestion
python -m sglang.lang.launch_debug_server
```

2024-11-09 23:32 UTC, merrymercy commented on python/sglang/README.md
> +- `launch_debug_server.py`: The entry point for launching the debug server + web app
This is an experimental feature for frontend language only, so please move it under `python/sglang/lang`.

2024-11-09 23:32 UTC, merrymercy commented on python/sglang/lang/backend/vertexai.py
> +        s.log_debug(
It is better to add `s.log_debug` to `interpreter.py` so we do not need to do it for every backend file.

2024-11-09 23:35 UTC, merrymercy requested changes

2024-11-09 23:35 UTC, merrymercy commented on python/sglang/lang/backend/anthropic.py
> +        )
This is not efficient enough. When debug is turned off, you still run the code to construct the argument, which takes some time. Please minimize the overhead and do not construct any objects when debug is turned off.

2024-12-26 16:03 UTC, merrymercy commented
closed due to inactivity and low priority

2024-12-26 16:03 UTC, closed without merging