Fix issue with `stop_token_ids` not being iterable.
sgl-project/sglang pull request #1901
Opened 2024-11-03 12:58 UTC by inakineitor

## Motivation

Prevent `'Nonetype' object is not iterable' from being thrown on line 141 after instantiating `SamplingParams` without a `stop_token_ids` list and calling `to_srt_kwargs`. Since the documentation states that the default value is an empty list, there should be no problem in `self.stop_token_ids` being an empty set if not initial list is provided.

## Modifications

Made `self.stop_token_ids` be an empty set is no list of stop token ids is provided.

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
  - No unit tests appear to be necessary, although I can add if you notice something missing.
- [x] Update documentation as needed, including docstrings or example tutorials.
  - The [sampling params documentation](https://github.com/sgl-project/sglang/blob/main/docs/references/sampling_params.md) already had the empty list as the default value.

2024-11-03 20:29 UTC, merrymercy requested changes
Could you provide an error traceback or code example?

2024-11-03 20:29 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_params.py
> +        stop_token_ids: Optional[List[int]] = [],
we should not use mutable objects as default arguments.

2024-11-08 03:57 UTC, merrymercy commented
@inakineitor Do you have any updates?

2024-11-08 07:03 UTC, closed without merging

2024-11-08 07:03 UTC, merrymercy commented
This is never used. see #1955

2024-11-08 09:47 UTC, inakineitor commented
Hi! Sorry I missed you previous message. I'm using `SamplingParams` class to have a type-checked way of passing in the sampling parameters to the `generate` method of the `Engine` class. Since `generate` accepts a dictionary, I use the `to_srt_kwargs` to convert the `SamplingParams` class instance to a dictionary before passing.

```python
sampling_params = SamplingParams(
    temperature=TEMPERATURE,
    n=bs,
    max_new_tokens=num_unique,
    stop_token_ids=[], 
)

out = model.generate(
    input_ids=[input_ids],
    sampling_params=sampling_params.to_srt_kwargs(),
)
```

Here is a reproduction of the error and a potential fix given that we asume the constructor types are correct ([Colab link](https://colab.research.google.com/drive/14Txw0nZSDBTouTpS_iguv_Bva7Bnw3ii?usp=sharing)). I can write tests for this if wanted.

If I misunderstood the use of the class please let me know. I would like to amend it in my code if so. Thank you!