fix black in pre-commit
sgl-project/sglang pull request #1940
Opened 2024-11-06 21:06 UTC by zhaochenyang20

## Motivation

Following https://github.com/sgl-project/sglang/pull/1938#discussion_r1831094180

I fixed the black hook in the pre-commit. I only changed `pre-commit-config.yaml`. The other changes are due to the new `black`.

@zhyncs 

## Modifications

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

2024-11-07 03:58 UTC, XuehaiPan requested changes

2024-11-07 03:58 UTC, XuehaiPan commented on .pre-commit-config.yaml
> +        files: '\.(py|ipynb)$'
Use `- id: black-jupyter`. It will do this trick for you.

See:

- https://github.com/sgl-project/sglang/pull/1938#discussion_r1831071218

2024-11-07 23:42 UTC, zhyncs approved these changes

2024-11-07 23:42 UTC, merged

2024-11-08 11:03 UTC, XuehaiPan commented on .pre-commit-config.yaml
> +        types: [jupyter]
```suggestion
      - id: black-jupyter
```

You only need to use `black-jupyter`. It defines `types_or: [python, pyi, jupyter]`.