benchmark json schema
sgl-project/sglang pull request #2030
Opened 2024-11-14 07:26 UTC by DarkSharpness

## Motivation

## Modifications

Add a simple benchmark about json schema constrained decoding, based on dataset [NousResearch/json-mode-eval](https://huggingface.co/datasets/NousResearch/json-mode-eval)

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

2024-11-14 07:58 UTC, merrymercy requested changes

2024-11-14 07:58 UTC, merrymercy commented on benchmark/json_schema/bench_sglang.py
> +    )
need to assert the output is a correct json and has the required keys.
https://github.com/sgl-project/sglang/blob/b275ce00439b07c8d73d9f11b6d0fb74dda46629/test/srt/test_json_constrained.py#L71-L78

2024-11-15 00:42 UTC, merrymercy requested changes

2024-11-15 00:42 UTC, merrymercy commented on benchmark/json_schema/bench_sglang.py
> +    tmpl = get_chat_template_by_model_path("Llama-3.1-8B-Instruct")
You do not need this. You can use https://github.com/sgl-project/sglang/blob/a10d5309436f83c34c1dc948f5601dd8895e7df2/python/sglang/test/test_programs.py#L45-L46

2024-11-15 00:42 UTC, merrymercy commented
Please fix the lint error and paste some benchmark results here. Then we can merge this!

2024-11-15 09:47 UTC, DarkSharpness commented
> Please fix the lint error and paste some benchmark results here. Then we can merge this!

Sure! Here's some experiment results on my machine:

Configuration: `AMD EPYC 7302 16-Core Processor` + `NVIDIA A100 40G`

| Settings                             | Latency (s) | Overall output tokens |
| :----------------------------------- | ----------- | --------------------- |
| outlines + disk_cache + jump_forward | 59.788      | 5580                  |
| outlines + disk_cache - jump_forward | 57.645      | 5081                  |
| outlines - disk_cache + jump_forward              | 456.94     | 5580                  |
| outlines - disk_cache - jump_forward              | 451.79      | 5081                  |

1. the overall output tokens should be identical in all cases, but due to [this bug](https://github.com/sgl-project/sglang/issues/2025), the actual output differs slightly
2. disk_cache means that the compiled regex/json_schema is already in disk cache before running, so we don't need to recompile that when running (which results in a significant speed up).

2024-11-15 10:04 UTC, zhyncs commented
> disk_cache means that the compiled regex/json_schema is already in disk cache before running, so we don't need to recompile that when running (which results in a significant speed up).

This is basically done in all current implementations, including TensorRT LLM, and the `disk_cache` should be enabled by default.

2024-11-15 10:06 UTC, zhyncs commented
BTW how about this https://github.com/guidance-ai/llgtrt
It can reduce the first time compilation overhead.

2024-11-15 11:30 UTC, merrymercy requested changes

2024-11-15 11:30 UTC, merrymercy commented on benchmark/json_schema/README.md
> +python3 -m sglang.launch_server --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000 --mem-fraction-static 0.8 --disable-disk-cache
Instead of using men-fraction 0.8, can you try —chunked-prefill-size 2048?

mem-fraction 0.8 will hurt the throughput significantly

2024-11-15 11:30 UTC, merrymercy commented on benchmark/json_schema/bench_sglang.py
> +    dataset = dataset[:54] + dataset[55:]
Anyway to detect this automatically with code?

2024-11-15 11:30 UTC, DarkSharpness commented
> BTW how about this https://github.com/guidance-ai/llgtrt It can reduce the first time compilation overhead.

Thanks for the suggestion!

Currently, we plan to support [xgrammar](https://github.com/mlc-ai/xgrammar) as a faster grammar backend alternative.

Maybe we can give it [llgtrt](https://github.com/guidance-ai/llgtrt) a try in future PRs.

2024-11-15 11:32 UTC, merrymercy commented
@zhyncs disk cache is turned on by default. xgrammar will solve the preprocess slowness

2024-11-15 11:32 UTC, DarkSharpness commented on benchmark/json_schema/README.md
> +python3 -m sglang.launch_server --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000 --mem-fraction-static 0.8 --disable-disk-cache
sure, i will remove that. that's just a parameter for my machine (without `--men-fraction 0.8`, the sglang server may crash)

2024-11-15 11:37 UTC, DarkSharpness commented on benchmark/json_schema/bench_sglang.py
> +    dataset = dataset[:54] + dataset[55:]
Currently, the skipped json schema triggered the following error:

```
e=NotImplementedError('Format email is not supported by Outlines')
```

Maybe we can skip all json_schema with format email?

2024-11-15 11:40 UTC, merrymercy commented on benchmark/json_schema/README.md
> +python3 -m sglang.launch_server --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000 --mem-fraction-static 0.8 --disable-disk-cache
This is a bug of sglang. We should fix it. Can you add a check in sglang and automatically set a set of correct default value for GPUs with 24 GB memory?

2024-11-15 11:42 UTC, merrymercy commented on benchmark/json_schema/bench_sglang.py
> +    dataset = dataset[:54] + dataset[55:]
Sounds good

2024-11-15 11:53 UTC, DarkSharpness commented on benchmark/json_schema/README.md
> +python3 -m sglang.launch_server --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000 --mem-fraction-static 0.8 --disable-disk-cache
OK. But I'm not quite sure where should I add these checkings and modify the user-provided arguments.

2024-11-15 12:18 UTC, Ying1123 commented on benchmark/json_schema/README.md
> +python3 -m sglang.launch_server --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000 --mem-fraction-static 0.8 --disable-disk-cache
You can set it after here https://github.com/sgl-project/sglang/blob/29ebe3dff475b87f9e252fa9257ab9b64ee4988f/python/sglang/srt/server_args.py#L142-L157

2024-11-15 13:06 UTC, merged

2024-11-15 13:36 UTC, merrymercy commented on benchmark/json_schema/README.md
> +python3 -m sglang.launch_server --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000 --mem-fraction-static 0.8 --disable-disk-cache
I will fix this

2024-11-15 13:59 UTC, merrymercy commented on benchmark/json_schema/README.md
> +python3 -m sglang.launch_server --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000 --mem-fraction-static 0.8 --disable-disk-cache
#2044