Input_embeds support
sgl-project/sglang pull request #2052
Opened 2024-11-16 12:01 UTC by RinRin-32

## Motivation

Adding input_embeds support for sglang, motivated and inspired from
https://github.com/sgl-project/sglang/issues/745

## Modifications

Changes in /manager to support new io_struct
Changes in /model_executor to support new io_struct
test cases under test/srt to demonstrate usage

In this implementation, curl request has to be made to use input_embeds.
This implementation DOES NOT have ARGS made to compliment input_embeds (I don't know where to make this edit),

When serving, to use input embeds please add 
`--disable-radix` tag
i.e.
`python3 -m sglang.launch_server --model-path Qwen/Qwen2.5-0.5B --port 30000 --disable-radix`

test_input_embeddings.py is built and tested on Qwen2.5-0.5B, please edit the model name according to the model that you'd like to test

input_embeddings.json is my test case embeddings for Qwen2.5-0.5B model and comparison_response.txt is a comparison between text based input and input_embeds input.

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

2024-11-18 21:01 UTC, merrymercy commented
Thanks for the contribution. There is a related PR recently. Can you take a review on that? #2082

2024-11-19 12:34 UTC, RinRin-32 commented
> Thanks for the contribution. There is a related PR recently. Can you take a review on that? #2082

It seems that this PR update the documents and did more alteration with batch in mind. If their implementation doesn't require radix disabled then it'd be the perfect one among the 2 pr. My changes follow the guide in that open issue and is pretty minimal, with test to try out the feature.

Also can you please launch the checks again, I fixed some conditions since the last check you triggered, thank you.

2024-11-22 09:30 UTC, merrymercy requested changes
Thanks for the contribution. I feel your solution is better than the other one. We can try to merge yours! I left a few comments.

2024-11-22 09:30 UTC, merrymercy commented on python/sglang/srt/managers/schedule_batch.py
> +        input_embeds: Optional = None,
Fill in the type annotation: Optional[what]?

2024-11-22 09:30 UTC, merrymercy commented on python/sglang/srt/managers/schedule_batch.py
> +    input_embeds: Optional[Union[List[List[List[float]]], List[List[float]]]] = None
can you make it a tensor at this stage?

2024-11-22 09:30 UTC, merrymercy commented on python/sglang/srt/managers/schedule_batch.py
> +    input_embeds: Optional[Union[List[List[List[float]]], List[List[float]]]] = None
it is already a tensor here.

2024-11-22 09:30 UTC, merrymercy commented on python/sglang/srt/managers/scheduler.py
> +            input_embeds_tensor = torch.tensor(recv_req.input_embeds)
this conversion seems not to be used and it causes extra overhead.

2024-11-22 09:30 UTC, merrymercy commented on python/sglang/srt/model_executor/forward_batch_info.py
> +                batch.input_embeds.clone().detach().to(device)
remove this clone

2024-11-22 09:30 UTC, merrymercy commented on test/srt/test_input_embeddings.py
> +import torch
This looks good! Can you make it a unit test like the following examples
https://github.com/sgl-project/sglang/blob/main/test/srt/test_srt_endpoint.py
https://github.com/sgl-project/sglang/blob/main/test/srt/models/test_generation_models.py

2024-11-22 09:30 UTC, merrymercy commented on python/sglang/srt/managers/tokenizer_manager.py
> +            input_ids = obj.input_ids
we can assert `self.server_args.disable_radix_cache = False` here and return and raise a useful warning message.

2024-11-22 09:50 UTC, merrymercy commented
1. Can you fix the conflicts?
2. I added you as a co-author in this merged PR so you are not a first-time contributor anymore. The CI will be triggered automatically for any of your future commits. https://github.com/sgl-project/sglang/pull/2122

2024-11-25 08:27 UTC, RinRin-32 commented
I apologize for the slow reply.
Will get to it as soon as I can. Expect it done in a week!

2024-11-26 00:35 UTC, merged