Online weight update [WIP]
sgl-project/sglang pull request #2119
Opened 2024-11-22 03:20 UTC by zhaochenyang20

## Motivation

## Modifications

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

2024-11-22 11:48 UTC, zhyncs requested changes

2024-11-22 11:48 UTC, zhyncs commented on test/srt/stderr.txt
Delete this, it's useless.

2024-11-22 11:48 UTC, zhyncs commented on test/srt/stdout.txt
Delete this, it's useless.

2024-11-22 11:48 UTC, zhyncs commented on test/srt/test_init_parameter_update_group.py
> +            # 设置分布式环境
Do not use Chinese annotations.

2024-11-24 14:53 UTC, merrymercy commented
You can rebase and add your 2-gpu test here https://github.com/sgl-project/sglang/blob/fa271613809bc5d901c0e864c4f9b9d3d3a101bd/.github/workflows/pr-test.yml#L106-L109

2024-11-28 01:32 UTC, closed without merging