Speculative EAGLE2.   New PR
sgl-project/sglang pull request #2150
Opened 2024-11-24 02:23 UTC by yukavio

Create a new PR for supporting speculative decoding with EAGLE2. The old one is https://github.com/sgl-project/sglang/pull/1498.

2024-11-24 03:02 UTC, merrymercy requested changes

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch: ForwardBatch = None,
Style. If one argument can be None, we should use "Optional[xx] instead of xxx"

```suggestion
        encoder_lens: Optional[torch.Tensor] = None,
        spec_info: Optional["SpecInput"] = None,
        is_draft_runner: bool = False,
        forward_batch: Optional[ForwardBatch] = None,
```

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch=None,
correct the type annotation, use `Optional`

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +            (max_bs * (self.max_context_len + 7) // 8),
why is a rounding needed here?

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +        if spec_info is not None and not is_draft_runner:
we can use forward_mode.is_target_verify() as a condition.

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +        is_draft_runner: bool = False,
is_draft_runner seems not useful.

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +        forward_batch=None,
keep type annotations.

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +                and forward_batch.forward_mode.is_target_verify()
I think they will always be true at the same time? Why do you need an "and"?

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +            kv_indices, kv_indptr, kv_last_page_len, qo_indptr = (
Do not pass the whole `forward_batch.spec_info` here. Only pass what is needed to compute `kv_indices, kv_indptr, kv_last_page_len, qo_indptr` here.

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/layers/logits_processor.py
> +    next_token_logits_bak: Optional[torch.Tensor] = None
We can back up it somewhere else. Not this is always the same as `next_token_logits`. It seems redundant if a function returns two same values.

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/managers/data_parallel_controller.py
> +                sockets.append(bind_port(tmp_port_args.nccl_port[0]))
use another variable instead of making it a list.

2024-11-24 03:02 UTC, merrymercy commented on python/sglang/srt/managers/scheduler.py
> +                        self.draft_worker.forward_batch_speculative_generate(batch)
`model_worker_batch` is the input, not output. If you want to return some output, create a new data structure for it. Use correct name to make it clear whether it is an input or an output of a function.

2024-12-02 04:12 UTC, qibaoyuan commented
forward_draft_decode, forward_batch ForwardBatch(forward_mode=<ForwardMode.DECODE: 3>, **batch_size=1**, **input_ids**=tensor([112365,  93418,  97358,  96001,   7600,  13737,  18821,   2820],
       device='cuda:0'), req_pool_indices=tensor([1], device='cuda:0', dtype=torch.int32), seq_lens=tensor([1097], device='cuda:0', dtype=torch.int32), out_cache_loc=tensor([2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500], device='cuda:0',
       dtype=torch.int32), seq_lens_sum=1097, return_logprob=False, top_logprobs_nums=None, **positions**=tensor([1097, 1097, 1097, 1097], device='cuda:0'), extend_num_tokens=None, extend_seq_lens=None, extend_prefix_lens=None, extend_start_loc=None, extend_prefix_lens_cpu=None, extend_seq_lens_cpu=None, extend_logprob_start_lens_cpu=None,....

Any idea on this problem? it seems that bs=1, but input_ids and positions did not match.

2024-12-05 07:06 UTC, yukavio commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +                forward_batch=forward_batch,
In fact, we need that to maintain the information about eagle2 in verify stage and draft decode stage.

2024-12-05 07:24 UTC, yukavio commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +            (max_bs * (self.max_context_len + 7) // 8),
The argument of 'max_bs' in the verify stage means the number of input tokens of the target model instead of the number of requests. But we only need the mask have shape with the max numbers of number of requests. 
Divide 8 is a bug due to the pre-version the number-of-token=number-of-request*8, but now is depends on inputs argument. 
I will change it to `max_bs * self.max_context_len` for convenient. And it would not waste too much memory.

2024-12-05 11:05 UTC, yukavio commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +            kv_indices, kv_indptr, kv_last_page_len, qo_indptr = (
But the method that computes these is implemented by spec_info class.

2024-12-09 03:17 UTC, bisunny commented
A problem is that when tp>1, only the rank0 cuda graph takes effect.

2024-12-10 01:18 UTC, liangan1 commented
@merrymercy This PR is too large(2000+lines) to understand it in a short time, whether should split multiple small PRs to speedup the review process?

2024-12-10 02:49 UTC, yukavio commented
> forward_draft_decode, forward_batch ForwardBatch(forward_mode=<ForwardMode.DECODE: 3>, **batch_size=1**, **input_ids**=tensor([112365, 93418, 97358, 96001, 7600, 13737, 18821, 2820], device='cuda:0'), req_pool_indices=tensor([1], device='cuda:0', dtype=torch.int32), seq_lens=tensor([1097], device='cuda:0', dtype=torch.int32), out_cache_loc=tensor([2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500], device='cuda:0', dtype=torch.int32), seq_lens_sum=1097, return_logprob=False, top_logprobs_nums=None, **positions**=tensor([1097, 1097, 1097, 1097], device='cuda:0'), extend_num_tokens=None, extend_seq_lens=None, extend_prefix_lens=None, extend_start_loc=None, extend_prefix_lens_cpu=None, extend_seq_lens_cpu=None, extend_logprob_start_lens_cpu=None,....
> 
> Any idea on this problem? it seems that bs=1, but input_ids and positions did not match.

The bs is not equal to the number of input tokens of the model  in the verify stage and draft decode stage.

2024-12-10 02:51 UTC, yukavio commented
> A problem is that when tp>1, only the rank0 cuda graph takes effect.
Sorry, this PR is not currently tested on TP>1. This PR is too large now. I would support it after merging this PR.

2024-12-10 02:51 UTC, yukavio commented
> > A problem is that when tp>1, only the rank0 cuda graph takes effect.
> > Sorry, this PR is not currently tested on TP>1. This PR is too large now. I would support it after merging this PR.

2024-12-12 09:59 UTC, coolhok commented
Concurrent requests can cause crashes。

2024-12-16 02:08 UTC, yukavio commented
> Concurrent requests can cause crashes。

Sorry, How can I reproduce this problem?

2024-12-20 08:44 UTC, bisunny commented
When prefixcache is enabled, the draft model incorrectly uses the req_to_token of the target model !

2024-12-20 09:00 UTC, yukavio commented
> When prefixcache is enabled, the draft model incorrectly uses the req_to_token of the target model !

We don't support prefix cache currently.

2024-12-20 09:37 UTC, bisunny commented
> > When prefixcache is enabled, the draft model incorrectly uses the req_to_token of the target model !
> 
> We don't support prefix cache currently.

Well, do you have a time plan for prefixcache?

2024-12-25 10:25 UTC, BucherLi commented
I found that the generation does not stop even when it encounters the end token ID when I tested using the script "test/srt/test_eagle_infer.py"
 
![image](https://github.com/user-attachments/assets/36b7c6ec-4e62-4c4e-b616-ed56999d372f)

2024-12-28 01:57 UTC, merrymercy commented on examples/runtime/engine/EAGLE_offline_batch_inference.py
> +        num_draft_tokens=16,
```suggestion
        speculative_algorithm="EAGLE",
        speculative_draft_model_path="kavio/Sglang-EAGLE-llama2-chat-7B",
        speculative_num_steps=3,
        speculative_expand_topk=4,
        speculative_num_draft_tokens=16,
```

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch: Optional[ForwardBatch] = None,
Should make this explicit. i.e., include all needed values instead of passing the big `ForwardBatch`

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/layers/attention/__init__.py
> +        forward_batch: Optional[ForwardBatch],
revert this?

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +        if forward_batch.forward_mode.is_target_verify():
Reverse the order of these two branches. Put the common branch as the first branch.

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +            self.forward_metadata = (use_ragged, extend_no_prefix, None)
None is graph_wrapper. TODO(lianmin): annotate the type of `self.forward_metadata`

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/layers/attention/flashinfer_backend.py
> +                forward_batch.spec_info.generate_attn_arg_spec_extend(
I think we can keep the current code, but only pass `forward_batch.ForwardMode` and `spec_info`

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/layers/attention/triton_backend.py
>          # NOTE: encoder_lens expected to be zeros or None
assert spec_info is None

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/managers/schedule_batch.py
> +    spec_info: SpecInput = None
```suggestion
    spec_input: SpecInput = None
```

2024-12-28 01:57 UTC, merrymercy commented on python/sglang/srt/managers/schedule_batch.py
> +    spec_algorithm: SpeculativeAlgorithm = SpeculativeAlgorithm.NONE
```suggestion
    spec_algorithm: SpeculativeAlgorithm = None
```

2024-12-28 06:17 UTC, merrymercy commented on python/sglang/srt/speculative/__init__.py
> +from .eagle_worker import EAGLEWorker
use absolute import

2024-12-28 06:17 UTC, merrymercy commented on python/sglang/srt/speculative/build_eagle_tree.py
> +
now we have sgl-kernels so we can also put the kernels there

2024-12-28 06:17 UTC, merrymercy commented on python/sglang/srt/speculative/eagle_utils.py
> +def create_flashinfer_kv_indices_triton(
can do lazy import

2024-12-28 06:17 UTC, merrymercy commented on python/sglang/srt/speculative/eagle_utils.py
> +        assert self.topk <= 10, "topk should <= 10"
Why is this?

2025-01-02 04:43 UTC, merrymercy commented
TODO:
1. (minor) support larger top-k
2. support temp != 0.    @lianmin
3. support tp > 1.  Add a new argument `--draft-tp-size 4`.   @lianmin
4. chunked prefill
5. (optional) prefix sharing
6. bug: a bug in retract
7. misc: logprob, stop condition, log, metrics, ...
8. set spec parameters according to batch size
9. train a better draft model

2025-01-02 11:22 UTC, merged

2025-01-02 11:31 UTC, zhyncs commented
🎉🎉🎉

2025-01-16 12:15 UTC, Xu-Chen commented
When the batch size increases, the time taken for eagle_verify_retrive increases considerably. When the batch_size is increased to 10, the eagle_verify_retrive time increases to 0.15s for the 70b model on 4*A100, resulting in a slow overall throughput speed.

2025-01-17 02:06 UTC, yukavio commented
> 当 batch size 增加时，eagle_verify_retrive 所需的时间会大幅增加。当 batch_size 增加到 10 时，对于 4*A100 上的 70b 模型，eagle_verify_retrive 时间增加到 0.15 秒，导致整体吞吐速度变慢。

Thanks for your report. I'll go confirm this. and look for possible solutions.

2025-01-20 10:55 UTC, mmdbhs commented
can it used in awq model?

2025-01-21 02:33 UTC, Xu-Chen commented
> can it used in awq model?

You need to train the eagle model based on the awq model, and then you can use it. 
Since the hidden states of transformer and sglang have certain precision differences, the acceleration effect will be discounted.

2025-01-21 02:34 UTC, Xu-Chen commented
> Thanks for your report. I'll go confirm this. and look for possible solutions.

Is there any progress？ @yukavio

2025-01-21 08:20 UTC, yukavio commented
> > Thanks for your report. I'll go confirm this. and look for possible solutions.
> 
> Is there any progress？ @yukavio

I found only the first execution of the kernel is slow and it will not result in a slow overall throughput speed.

2025-01-21 12:32 UTC, Xu-Chen commented
> H800

Not sure if it's an A800(sm80) issue. 
According to my test results on 4 * A800, model: Qwen2-72B-instruct.
When BS=1, the TPS of a single request is 75; when BS=10, the overall TPS = 230 - 260, and the average TPS of a single request is only 25.


Test Code
```python
import argparse
import time
from openai import OpenAI
from multiprocessing import Pool
def infer_one(pid, openai_api_base, model_name, num):
    openai_api_key = "EMPTY"
    client = OpenAI(api_key=openai_api_key, base_url=openai_api_base)
    start_time = time.time()
    messages = [{"role": "user", "content": "以模型部署与推理加速为题，写一篇少于 2000 字的文章"}]
    llm_response = client.chat.completions.create(
        messages=messages,
        model=model_name,
        max_tokens=2048,
        temperature=0,
        stream=True
    )
    if pid == 0:
        print("\n########## start ##########")
    answer = ""
    num_token = 0
    for each in llm_response:
        if len(each.choices) == 0:
            continue
        content = each.choices[0].delta.content
        if content is not None:
            answer += content
            num_token += 1
            if pid == 0:
                print(content,end="",  flush=True)
    if pid == 0:
        print("\n########## end  ############")

def infer_main(pid, openai_api_base, model_name):
    for i in range(3):
        infer_one(pid, openai_api_base, model_name, i)

def parser_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pid-num",
        type=int,
        help="work num",
        default=5,
    )
    parser.add_argument(
        "--host",
        type=str,
        help="host",
        default="",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        help="model name",
        default="",
    )
    args = parser.parse_args()
    return args

if __name__ == '__main__':
    args = parser_args()
    print(args)
    pid_num = args.pid_num
    model_name = args.model_name
    openai_api_base = f"{args.host}/v1"
    assert openai_api_base != ""
    pool = Pool(processes=pid_num)
    process_list = []
    start_time = time.time()
    for i in range(pid_num):
        p = pool.apply_async(infer_main, (i, openai_api_base, model_name,))
        process_list.append(p)
    pool.close()
    pool.join()
```

2025-01-22 02:31 UTC, yukavio commented
Sorry, I don't have the A800 for testing. Could you please give me a profile file of nsight-system of of your test? (Don't test too many requests. It will cause the file too large to open in a laptop) I could help you to find the problem that caused the server to slow.

2025-01-22 03:56 UTC, Xu-Chen commented
> Sorry, I don't have the A800 for testing. Could you please give me a profile file of nsight-system of of your test? (Don't test too many requests. It will cause the file too large to open in a laptop) I could help you to find the problem that caused the server to slow. @Xu-Chen

I will try to generate test reports with nsight-systems-cli, thanks for your help. @yukavio

2025-01-22 15:24 UTC, Xu-Chen commented
> Sorry, I don't have the A800 for testing. Could you please give me a profile file of nsight-system of of your test? (Don't test too many requests. It will cause the file too large to open in a laptop) I could help you to find the problem that caused the server to slow. @Xu-Chen 

I generate test reports with nsight-systems-cli on 4 * A100,  [sglang.out-v1.nsys-rep.zip](https://github.com/user-attachments/files/18507685/sglang.out-v1.nsys-rep.zip), thanks for your help. @yukavio

2025-01-23 03:21 UTC, yukavio commented
> 230 - 260



> > H800
> 
> Not sure if it's an A800(sm80) issue. According to my test results on 4 * A800, model: Qwen2-72B-instruct. When BS=1, the TPS of a single request is 75; when BS=10, the overall TPS = 230 - 260, and the average TPS of a single request is only 25.
> 
> Test Code
> 
> ```python
> import argparse
> import time
> from openai import OpenAI
> from multiprocessing import Pool
> def infer_one(pid, openai_api_base, model_name, num):
>     openai_api_key = "EMPTY"
>     client = OpenAI(api_key=openai_api_key, base_url=openai_api_base)
>     start_time = time.time()
>     messages = [{"role": "user", "content": "以模型部署与推理加速为题，写一篇少于 2000 字的文章"}]
>     llm_response = client.chat.completions.create(
>         messages=messages,
>         model=model_name,
>         max_tokens=2048,
>         temperature=0,
>         stream=True
>     )
>     if pid == 0:
>         print("\n########## start ##########")
>     answer = ""
>     num_token = 0
>     for each in llm_response:
>         if len(each.choices) == 0:
>             continue
>         content = each.choices[0].delta.content
>         if content is not None:
>             answer += content
>             num_token += 1
>             if pid == 0:
>                 print(content,end="",  flush=True)
>     if pid == 0:
>         print("\n########## end  ############")
> 
> def infer_main(pid, openai_api_base, model_name):
>     for i in range(3):
>         infer_one(pid, openai_api_base, model_name, i)
> 
> def parser_args():
>     parser = argparse.ArgumentParser()
>     parser.add_argument(
>         "--pid-num",
>         type=int,
>         help="work num",
>         default=5,
>     )
>     parser.add_argument(
>         "--host",
>         type=str,
>         help="host",
>         default="",
>     )
>     parser.add_argument(
>         "--model-name",
>         type=str,
>         help="model name",
>         default="",
>     )
>     args = parser.parse_args()
>     return args
> 
> if __name__ == '__main__':
>     args = parser_args()
>     print(args)
>     pid_num = args.pid_num
>     model_name = args.model_name
>     openai_api_base = f"{args.host}/v1"
>     assert openai_api_base != ""
>     pool = Pool(processes=pid_num)
>     process_list = []
>     start_time = time.time()
>     for i in range(pid_num):
>         p = pool.apply_async(infer_main, (i, openai_api_base, model_name,))
>         process_list.append(p)
>     pool.close()
>     pool.join()
> ```

What command line did you use to start the service?

2025-01-23 03:52 UTC, Xu-Chen commented
> What command line did you use to start the service?

/opt/conda/bin/python3 -m sglang.launch_server --model  Qwen/Qwen2-72B-Instruct --speculative-algo EAGLE --speculative-draft ./eagle-qwen2-72b-instruct --speculative-num-steps 5 --speculative-eagle-topk 8 --speculative-num-draft-tokens 64 --mem-fraction 0.7 --cuda-graph-max-bs 16 --context-length 32768 --tp 4 --port 8080 --dtype bfloat16

./eagle-qwen2-72b-instruct is [EAGLE-Qwen2-72B-Instruct](https://huggingface.co/yuhuili/EAGLE-Qwen2-72B-Instruct), change Qwen2ForCausalLM to Qwen2ForCausalLMEagle

2025-01-23 11:13 UTC, yukavio commented
It is reasonable that the TPS of each request will decrease as the batch size increases because speculative decoding is a method that helps us to improve the computation efficiency with small batch size. 
But you can try to set a smaller value of  'speculative-num-steps', 'speculative-eagle-topk' and 'speculative-num-draft-tokens' which will help you to get better performance with large batch size. @Xu-Chen

2025-01-23 11:40 UTC, Xu-Chen commented
> It is reasonable that the TPS of each request will decrease as the batch size increases because speculative decoding is a method that helps us to improve the computation efficiency with small batch size. But you can try to set a smaller value of 'speculative-num-steps', 'speculative-eagle-topk' and 'speculative-num-draft-tokens' which will help you to get better performance with large batch size. @Xu-Chen

You are so right. The following parameters can achieve up to 1.5X the speed at high concurrency. The parameter speculative-num-draft-tokens particularly affects performance at high batch-sizes ( we test 10).
```
--speculative-num-steps 3
--speculative-eagle-topk 4
--speculative-num-draft-tokens 16
```