Support top n sigma sampling
sgl-project/sglang pull request #2192
Opened 2024-11-26 06:07 UTC by Snowdar

## Motivation
Support a more complete samling options for decoding, especialy for openai compatible api.

## Modifications

1. Add the rencent [top-n-sigma samping](https://arxiv.org/html/2411.07641v1) as a decoding option and it will be applied to the logits after temperature applied when `top_n_sigma` > 0.  The batch processing has been implemented.
2. Add `top-k`, `min-p` and `top_n_sigma` params for openai compatible api server (Note, please add these three params by `extra_body` when using openai SDK)

client example:
```
client = OpenAI(api_key='no key', base_url='http://localhost:30000/v1')
response = client.chat.completions.create(
      model='llama',
      messages=dict(role='user', content='hi'),
      temperature=0.3,
      max_tokens=128,
      top_p=0.95,
      frequency_penalty=0.,
      presence_penalty=0.,
      extra_body=dict(
          min_p=0.,
          top_k=-1,
          top_n_sigma=1, # enable it
      ),
)
```

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

2024-12-01 08:44 UTC, merrymercy requested changes
Thanks for the contribution. I left a few comments.

2024-12-01 08:44 UTC, merrymercy commented on python/sglang/srt/openai_api/protocol.py
> +    top_k: int = -1
move this after L288

2024-12-01 08:44 UTC, merrymercy commented on python/sglang/srt/layers/sampler.py
> +            if any(sampling_info.top_n_sigmas > 0):
move this check to `sampling_batch_info.py` and name it `need_top_n_sigmas_sampling`, similar to how we do `need_min_p_sampling`.

2024-12-01 08:44 UTC, merrymercy commented on python/sglang/srt/layers/sampler.py
> +                )
To prevent this function from being too long, wrap this as a function and call it here.

2024-12-02 02:13 UTC, Snowdar commented
> Thanks for the contribution. I left a few comments.

OK. All of these have completed. Could you please view it again?

2024-12-17 12:11 UTC, merrymercy commented
`top-k` and `min-p` are fixed in https://github.com/sgl-project/sglang/pull/2499.
However, top n sigma is still not a common sampling strategy, we may not want to maintain it in the core right now.
For these things, it is better to support them via a custom logit processer interface. Can you help review this issue? https://github.com/sgl-project/sglang/issues/2291

I will close this for now.

2024-12-17 12:11 UTC, closed without merging

2024-12-18 05:29 UTC, Snowdar commented
> `top-k` and `min-p` are fixed in #2499. However, top n sigma is still not a common sampling strategy, we may not want to maintain it in the core right now. For these things, it is better to support them via a custom logit processer interface. Can you help review this issue? #2291
> 
> I will close this for now.

So if the custom logit processer could be supported，then any other sampling codes will not be merged into sglang (considering sharing the custom samping to other people by the sglang itself)?

2025-01-19 23:01 UTC, merrymercy commented
Hi @Snowdar ,

Custom logit processor is supported by https://github.com/sgl-project/sglang/pull/2396. We can implement this with the custom logit processor.

We can still accept new sampling method. We can create some built-in custom logit processor. Contributions are welcome!

2025-01-20 09:10 UTC, Snowdar commented
> Hi @Snowdar ,
> 
> Custom logit processor is supported by #2396. We can implement top n sigma with the custom logit processor.
> 
> We can still accept new sampling methods. We can merge some built-in custom logit processor into the sglang source code. Contributions are welcome!

OK. Good job! I will try this new method.

2025-01-21 09:23 UTC, hongpeng-guo commented
> OK. Good job! I will try this new method.

Here is an example of the custom logit processor :) https://docs.sglang.ai/references/sampling_params.html#custom-logit-processor