Update weights from dist
sgl-project/sglang pull request #2279
Opened 2024-11-30 08:20 UTC by zhaochenyang20

## Motivation

Following [OpenRLHF's vllm wrapper](https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/trainer/ray/vllm_worker_wrap.py), we support online weights updates from `torch.distributed`, which is hundreds of times quicker than saving the model to disk and updating the engine from disk.

Following these PRs:

https://github.com/sgl-project/sglang/pull/2265

https://github.com/sgl-project/sglang/pull/2266

## Modifications

I added three APIs in the server and engine, and added tests for them:

1. `init_parameter_update_group`
2. `update_parameter_from_distributed`
3. `get_weights_by_parameter_name`

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

2024-11-30 08:38 UTC, merrymercy requested changes

2024-11-30 08:38 UTC, merrymercy commented on .github/workflows/pr-test.yml
> +        timeout-minutes: 15
make it less than 3 mins actually and set the timeout to be 10 mins.

2024-11-30 08:38 UTC, merrymercy commented on python/sglang/srt/managers/tokenizer_manager.py
> +            obj.backend = "nccl"
set this default value in `io_struct.py`

2024-11-30 08:38 UTC, merrymercy commented on python/sglang/srt/server.py
> +            empty_cache=empty_cache,
drop this argument

2024-11-30 08:38 UTC, merrymercy commented on python/sglang/srt/utils.py
> +def init_custom_process_group(
use `init_process_group` instead

2024-11-30 08:38 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +        use_engine,
```suggestion
        backend: str,
```

2024-11-30 08:38 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    def setUpClass(cls):
move this to top.

2024-11-30 08:38 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +            DEFAULT_SMALL_MODEL_NAME_FOR_TEST,
only test one model on CI

2024-11-30 08:38 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +                    hf_instruct_params = results.get("hf_instruct_params")
split this into multiple functions.

2024-12-01 01:13 UTC, zhaochenyang20 commented on python/sglang/srt/utils.py
> +def init_custom_process_group(
How to init process group twice?

2024-12-01 01:14 UTC, zhaochenyang20 commented on python/sglang/srt/server.py
> +            empty_cache=empty_cache,
```python
    def update_weights_from_distributed(self, name, dtype, shape, empty_cache=False):
        obj = UpdateWeightsFromDistributedReqInput(
            name=name,
            dtype=dtype,
            shape=shape,
            empty_cache=empty_cache,
        )
        loop = asyncio.get_event_loop()
        return loop.run_until_complete(
            update_weights_from_distributed_request(obj, None)
        )
```

I don't think these can be dropped?

2024-12-01 06:03 UTC, merrymercy requested changes

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/managers/io_struct.py
> +    empty_cache: bool
remove this

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/managers/tokenizer_manager.py
> +        else:
`assert self.server_args.dp_size != 1`

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/managers/tokenizer_manager.py
> +            self.init_parameter_update_group_tmp = []
`assert self.server_args.dp_size == 1` in all cases.

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/managers/tokenizer_manager.py
> +                    self.init_parameter_update_group_tmp.append(recv_obj)
`assert self.server_args.dp_size == 1` in all cases.

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/managers/io_struct.py
> +    group_name: str
assign a default value here `weight_update_group`

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/model_executor/model_runner.py
> +        ), f"dtype mismatch: target={dtype} vs current model runner={self.dtype}"
remove this assert.

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/model_executor/model_runner.py
> +                torch.cuda.empty_cache()
remove this

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/models/llama.py
> +        # default tie_word_embeddings is True in SGLang
remove this

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/models/llama.py
> +            )
remove this; use a comment

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/server.py
> +app.put("/generate")(generate_request)
remove this

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/server.py
> +async def init_parameter_update_group_request(
move these functions to `class Engine`

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/server.py
>  async def get_weights_by_name_request(obj: GetWeightsByNameReqInput, request: Request):
move this to `class Engine`

2024-12-01 06:03 UTC, merrymercy commented on test/srt/test_get_weights_by_name.py
> +class TestUpdateWeights(unittest.TestCase):
fix name

2024-12-01 06:03 UTC, merrymercy commented on test/srt/test_get_weights_by_name.py
> +            self.init_hf_model(test_suit[-1], tie_word_embeddings)
```suggestion
            self.init_hf_model(test_suit[-1], tie_word_embeddings)
            self.init_backend(*test_suit)
```
revert the change of `mem-fraction-static`

2024-12-01 06:03 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +        truncate_size = 10
fix indentation

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/utils.py
> +# https://github.com/pytorch/pytorch/blob/main/torch/distributed/distributed_c10d.py
Add the link to OpenRLHF code

2024-12-01 06:03 UTC, merrymercy commented on python/sglang/srt/utils.py
> +)
move these imports under `init_custom_process_group`

2024-12-01 10:01 UTC, merrymercy requested changes

2024-12-01 10:01 UTC, merrymercy commented on test/srt/test_get_weights_by_name.py
> +        print(f"assert_tie_word_embeddings")
truncate_size = 100 and use `truncate_size` later

2024-12-01 10:01 UTC, merrymercy commented on test/srt/test_get_weights_by_name.py
> +            ("Runtime", 1, 1, DEFAULT_SMALL_MODEL_NAME_FOR_TEST),
only test a small model to save CI time.

2024-12-01 10:01 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +            (1, 1, DEFAULT_SMALL_MODEL_NAME_FOR_TEST, "Engine"),
only test a small model on CI to save time, you can skip tests if  the env var `SGLANG_IS_IN_CI` is true

2024-12-02 01:26 UTC, merrymercy requested changes

2024-12-02 01:26 UTC, merrymercy commented on python/sglang/srt/server.py
> +                return ORJSONResponse(
This is not an HTTP server, it can directly raise the error without `try except`

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_get_weights_by_name.py
> +                dp_size=dp,
Does it support DP? I do not think so

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +            )
Move these under `else`. Later, we might run this on a machine with more GPUs in CI.

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +        ]:
if it is in ci, we do not need to load the big model

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +from calendar import month_name
remove this

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    os.environ["NCCL_NVLS_ENABLE"] = "0"
Comment that these env vars are very important. Otherwise, it will lead to unknown CUDA errors.

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    hf_instruct_model = AutoModelForCausalLM.from_pretrained(
Add comment
```
# Load model
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    print(f"rank {rank} world_size: {world_size} init custom process group")
```suggestion

    # Init weight update group
    print(f"rank {rank} world_size: {world_size} init custom process group")
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    for parameter_name in broadcast_parameters:
```suggestion

    # Broadcast all weights
    for parameter_name in broadcast_parameters:
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    broadcast_time = time_end_broadcast - time_begin_broadcast
```suggestion

    # Measure latency
    broadcast_time = time_end_broadcast - time_begin_broadcast
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    instruct_params = []
```suggestion

    # Get original weights
    instruct_params = []
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    if backend == "Engine":
```suggestion

    # Init weight update group
    if backend == "Engine":
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    for parameter_name in update_parameters:
```suggestion

    # Broadcast all weights
    for parameter_name in update_parameters:
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    time_end_update = time.time()
```suggestion

    # Measure latency
    time_end_update = time.time()
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    base_params = []
```suggestion

    # Get the parameters after weight update for correctness check
    base_params = []
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    if backend == "Engine":
```suggestion

    # Shutdown
    if backend == "Engine":
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    params_to_check = [
```suggestion

    # Check embedding
    params_to_check = [
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    for i in range(len(params["hf_instruct"])):
```suggestion

    # Check parameters match after weight updates
    for i in range(len(params["hf_instruct"])):
```

2024-12-02 01:26 UTC, merrymercy commented on test/srt/test_update_weights_from_distributed.py
> +    def test_update_weights_from_distributed(self):
Add one short description here like the following:
This test will use the online weight update API to broadcast the weights from a process that holds a huggingface model to multiple sglang servers. The sglang servers originally load the base model weights and then we update it with the instruct model weights. After that, we check the weights are updated correctly.

2024-12-02 01:26 UTC, merrymercy commented on python/sglang/srt/managers/scheduler.py
> +                success, message = self.init_parameter_update_group(recv_req)
rename all
`init_parameter_update_group` -> `init_weights_update_group`
`InitParameterUpdateGroupReqInput` -> `InitWeightsUpdateGroupReqInput`

2024-12-02 07:23 UTC, merrymercy approved these changes

2024-12-02 07:23 UTC, merged

2025-12-23 12:05 UTC, EduardDurech commented
@zhaochenyang20 for future reference https://peps.python.org/pep-0440
```python
>>> "2.10"<"2.6"
True
```

Fixed in https://github.com/sgl-project/sglang/pull/15682