Add sampler logit processor
sgl-project/sglang pull request #2396
Opened 2024-12-08 09:39 UTC by hongpeng-guo

## Motivation
This PR tries to support custom logit processors registered by users, so users can easily implement their custom sampling methods without the need to change the sglang code.

## Related Issue
#2291 

## Modifications

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

2024-12-17 12:13 UTC, merrymercy commented
Thanks for taking this. Can you add some end-to-end tests and examples?

2024-12-18 11:03 UTC, hongpeng-guo commented
> Thanks for taking this. Can you add some end-to-end tests and examples?

@merrymercy  Thanks for taking a look on this. I am still trying to understand the appropriate layer for the user to register their `customized_logit_processor`. The goal is to enable `customized_logit_processor` functionality without requiring changes to the internal `sglang` codebase. To achieve this, the function registration should occur at the API layer. The `customized_logit_processor_fn` and `custom_params` will then be passed from the program driver to the internal modules, such as `Sampler` and `SampleParams`.

If the above seems correct, I will try to get it reviewable within this week.

2024-12-26 16:14 UTC, merrymercy commented
Your proposal sounds good. We should be able to register this function with all interfaces.
Say, we should be able to support it with our native `/generate` api and the offline Engine API.

2024-12-30 13:16 UTC, merrymercy commented
I did a refactor here https://github.com/sgl-project/sglang/pull/2664 to make sure the returned logprobs are the real logprobs the engine is sampling from. Could you help to resolve the conflicts?

2024-12-31 09:38 UTC, hongpeng-guo commented
> I did a refactor here #2664 to make sure the returned logprobs are the real logprobs the engine is sampling from. It will create some conflicts with your PR. I am sorry for the inconvenience. Could you resolve the conflicts?

NP! Just resolved the conflicts and added a unit test following the pattern of #2664.

2025-01-03 08:02 UTC, DreamGenX commented
This looks nice.

It might be informative to have a benchmark, e.g. by reimplementing some simple processors like Top P and comparing performance with the "native" implementation.

As a side note, vLLM has similar custom logit processor interface (though it does not support batching, unlike yours), and there are some known issues (including performance) -- there are some efforts to address that https://github.com/vllm-project/vllm/issues/5423 https://github.com/vllm-project/vllm/pull/6273 -- might be worth taking a look.

2025-01-03 08:05 UTC, DreamGenX commented on python/sglang/srt/server.py
> +        custom_logit_processor: Optional[Union[List[str], str]] = None,
Is there a reason to pass them serialized as string here? The HTTP API could deserialize them before, while the Python API remains clean.

2025-01-03 08:05 UTC, DreamGenX commented on test/srt/test_srt_endpoint.py
> +                merged_params = {
Nit: Why wrap the tensor in the object?

2025-01-03 08:22 UTC, merrymercy requested changes
Thanks for the contribution. The code looks very clean! Can you address the comments and make sure it does not introduce any perf regression when no request is using the custom logits processor?

2025-01-03 08:22 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_batch_info.py
> +        custom_params_list = [r.sampling_params.custom_params for r in reqs]
Please only run this related code when any of the request in the batch needs custom params.
If none of them needs custom params, we should not run any for loop or `merge_custom_logit_processor`.

You can cache a variable `self.has_custom_param = any(r.sampling_params.custom_params for r in reqs)` in the beginning and only run related code when it is true. see examples
https://github.com/sgl-project/sglang/blob/0f9cc6d8d3c688eeb8d61e5e869a59d8d756044b/python/sglang/srt/managers/schedule_batch.py#L1078-L1082
https://github.com/sgl-project/sglang/blob/4686c33f450f74b050a004a6336c34c80c1abc85/python/sglang/srt/sampling/sampling_batch_info.py#L229-L230

2025-01-03 08:22 UTC, merrymercy commented on python/sglang/srt/layers/sampler.py
> +            for (
```suggestion
        # Apply the custom logit processors if registered in the sampling info.
        if sampling_info.custom_logit_processor is not None:
            self.apply_custom_logit_processor(logits, sampling_info. custom_logit_processor)
```

minor style comment: move this part into a separate function.

2025-01-03 08:22 UTC, merrymercy commented on python/sglang/srt/managers/io_struct.py
> +    # Custom logit processor (serialized function)
improve the docstring by pointing it to an usage example

2025-01-03 08:22 UTC, merrymercy commented on python/sglang/srt/sampling/custom_logit_processor.py
> +import dill
is this dependency necessary?

2025-01-03 08:22 UTC, merrymercy commented on test/srt/test_srt_endpoint.py
> +        self.assertNotEqual(base_response, custom_response)
The assertion is a little bit weak. Can we adjust the logits to make it always sample a token and assert on that?

2025-01-03 08:31 UTC, DreamGenX commented on python/sglang/srt/layers/sampler.py
> +                processor = CustomLogitProcessor.from_str(processor_str)
Could this be done once per request, rather than once per token?

2025-01-03 08:38 UTC, DreamGenX commented on python/sglang/srt/sampling/custom_logit_processor.py
> +    def from_str(cls, json_str: str):
Not sure how dill exactly works, but is there a possibility of arbitrary code execution from the HTTP API by sending arbitrary serialized python code here?

2025-01-03 09:00 UTC, merrymercy commented on python/sglang/srt/sampling/custom_logit_processor.py
> +    def from_str(cls, json_str: str):
Very good point here, probably we need some safety mechanism or only allow custom logit processor under a feature flag which is turned off by default.

2025-01-07 06:30 UTC, hongpeng-guo commented on test/srt/test_srt_endpoint.py
> +                merged_params = {
Good point! It's not necessary to wrap the tensor as a dict, and it's totally up to the user to define this UDF. I will update it to the cleanest way in the unit test and the PR description.

2025-01-07 09:00 UTC, hongpeng-guo commented on python/sglang/srt/server.py
> +        custom_logit_processor: Optional[Union[List[str], str]] = None,
I agree that passing a python native object to the `Engine.generate()` API is more intuitive. I am using serialized str just to make sure that `GenerateReqInput` contains only Pydantic compatible field, i.e, `obj = GenerateReqInput( ..., custom_logit_processor=...)` needs an serialized input. Please let me know if there are ways to make it cleaner :)

2025-01-07 09:29 UTC, hongpeng-guo commented on python/sglang/srt/sampling/custom_logit_processor.py
> +    def from_str(cls, json_str: str):
I agree with (1) that running arbitrary UDFs increases the attack surface, and (2) it's safer to keep this feature off by default.

Random thought: An alternative could be treating this PR as a "plugin" framework, allowing SGL to maintain a side library of custom logit processors. These processors could be standalone components (subclass of `CustomLogitProcessor`) defined in `custom_logit_processor.py`, ensuring that no other files need modification. By default, only a "whitelisted" set of processors would be permitted. Users could enable a feature flag to experiment with niche processors if needed.

2025-01-07 09:30 UTC, hongpeng-guo commented on python/sglang/srt/sampling/sampling_batch_info.py
> +        custom_params_list = [r.sampling_params.custom_params for r in reqs]
sounds good!

2025-01-07 09:39 UTC, hongpeng-guo commented on python/sglang/srt/sampling/custom_logit_processor.py
> +import dill
`dill` is like an advanced version of `pickle`, covering more complicated objects, i.e., functions with yields, nested functions, lambdas, etc. https://dill.readthedocs.io/en/latest/

I think `dill` may works better here, e..g., a complicated logit processor `__call__` may contain nested functions to modularize its logic, which is covered by `dill` but not `pickle`

2025-01-07 09:40 UTC, hongpeng-guo reviewed
Replied comments & discussion. Will update PR shortly.

2025-01-09 08:00 UTC, hongpeng-guo commented on test/srt/test_srt_endpoint.py
> +        self.assertNotEqual(base_response, custom_response)
Sounds good. It's a good idea of testing.

2025-01-09 08:12 UTC, hongpeng-guo commented on python/sglang/srt/managers/io_struct.py
> +    # Custom logit processor (serialized function)
Could you elaborate a bit here? i.e., where do you think is the best place to add an usage example in the code base. There is one example in the unit test, but I guess it's not the best way to reference to the test folder :)

2025-01-09 08:17 UTC, hongpeng-guo reviewed
Update: handled most comments (1) gated the branch of custom logit processor to avoid performance regression, (2) made unit test stronger by making logits deterministic & constant, (3) fix nits

TODO & Questions: (1) add usage example to somewhere in the codebase; (2) improve doc str referencing to the examples.

2025-01-13 06:11 UTC, merrymercy requested changes
Some final comments on the style and performance. We can merge this after
1. Fixing the comments
2. Make this turned off by default for the security reasons. Add an option `--enable-custom-logits-processor`. If it is turned off and users send a request, print a suitable warning.

2025-01-13 06:11 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_batch_info.py
> +        self.custom_params = self.custom_params + other.custom_params
We should only run this when `self.has_custom_logit_processor or other.has_custom_logit_processor`

2025-01-13 06:11 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_batch_info.py
> +            custom_params=[r.sampling_params.custom_params for r in reqs],
If not `has_custom_logit_processor`, we should not even run this.

2025-01-13 06:11 UTC, merrymercy commented on test/srt/test_srt_endpoint.py
> +            def __call__(self, logits, custom_param_list, device):
I do not think we need `device`. We can just use `logits.device`

2025-01-13 06:11 UTC, merrymercy commented on test/srt/test_srt_endpoint.py
> +        self.assertEqual(len(set(sampled_tokens)), 1)
This test case is still not strong enough. Can we make it always sample token id "5"?

2025-01-13 06:11 UTC, merrymercy commented on python/sglang/srt/layers/sampler.py
> +                sampling_batch_info.device,
`sampling_batch_info.device,` is not needed.

2025-01-13 06:11 UTC, merrymercy commented on python/sglang/srt/layers/sampler.py
> +            processor = CustomLogitProcessor.from_str(processor_str)
This should be done once per request instead of per-token. You can cache it and use an integer as index later.

2025-01-17 11:16 UTC, DreamGenX commented
I am wondering what would be a good and safe way to expose this functionality. One option I possible flow I can imagine:

- Define your own logit processors in some python module, say `cool_processors` with `my_custom_logit_processor` processor function defined inside
- On your server, install sglang as well as `cool_processors`
- When starting the server, pass some flag like `--allowed_logit_processors=(some list or regex here)`, e.g. `--allowed_logit_processors=cool_processors.my_custom_logit_processor`
- At request time, pass the processor like this: `custom_logit_processor=cool_processors.my_custom_logit_processor`

This way we can control what code will be execxuted on the server when starting the server, rather than at request time.

2025-01-17 19:54 UTC, hanming-lu commented
@hongpeng-guo Thanks for contributing! Happy to see you here. May I ask what's the latest ETA on merging this PR? Thanks.

2025-01-17 19:57 UTC, hongpeng-guo commented
> @hongpeng-guo Thanks for contributing! Happy to see you here. May I ask what's the latest ETA on merging this PR? Thanks.

@hanming-lu Nice to see you here as well! Let me try to merge it before end of the week.

2025-01-17 23:31 UTC, hongpeng-guo commented
Update: all comments handled.

2025-01-18 05:34 UTC, DreamGenX commented on python/sglang/srt/sampling/sampling_batch_info.py
> +            has_custom_logit_processor=has_custom_logit_processor,
I don't know SGLang so well, but could we parse the logit processors in this function, when constructing the SamplingBatchInfo? This way you could avoid the whole hash + cache mechanism.

Alternatively, I would at least precompute the hash in this function (or just assign some unique index to each processor -- seems easier and more robust?), so that you can later reference it in the _apply_custom_logit_processor function for free.

2025-01-18 14:47 UTC, hongpeng-guo commented on python/sglang/srt/sampling/sampling_batch_info.py
> +            has_custom_logit_processor=has_custom_logit_processor,
Thanks for the proposal! I think it makes a lot of sense to me.

The current `custom_logit_processor` field in the `SamplingBatchInfo` is a dict of `{func_str: batch_mask}`. I have just updated it as a dict of `{int: (custom_logit_processor_obj, batch_mask)}`, where the key of the dict is `hash(processor_str)`. The UDF deserialization will happen on the scheduler process, and not the model processor `Sampler` anymore.

2025-01-19 03:32 UTC, hongpeng-guo reviewed
There are a few unit test on performance and accuracy being a bit flaky. they seem not to be directly related to this PR, though.

2025-01-19 04:40 UTC, merrymercy requested changes
We are almost there! Some final comments.

2025-01-19 04:40 UTC, merrymercy commented on python/sglang/srt/managers/schedule_batch.py
> +        enable_custom_logit_processor: bool = False,
The argument `enable_custom_logit_processor` is not needed. We can do the check in `scheduler.py` and avoid passing this argument here.

2025-01-19 04:40 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_batch_info.py
>      def merge_batch(self, other: "SamplingBatchInfo"):
We also need to implement `filter_batch`.

This also indicates that our test case is not strong enough, so it does not capture this bug.

Can you enhance the test case to cover batched settings? We can launch 32 threads, where thread `i` always generate token id `i`.
You can see this example https://github.com/sgl-project/sglang/blob/7906d1d29863bc3b33c4bcfb942a5d61f9867127/test/srt/test_json_constrained.py#L129-L132

2025-01-19 04:40 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_batch_info.py
> +                    CustomLogitProcessor.from_str(processor_str),
It is better to implement the caching logic inside `CustomLogitProcessor`.
Probably we can just use https://docs.python.org/3/library/functools.html#functools.lru_cache to decorate `CustomLogitProcessor.from_str`.

2025-01-19 05:43 UTC, hongpeng-guo commented on python/sglang/srt/managers/schedule_batch.py
> +        enable_custom_logit_processor: bool = False,
Sounds good.

2025-01-19 05:57 UTC, hongpeng-guo commented on python/sglang/srt/sampling/sampling_batch_info.py
>      def merge_batch(self, other: "SamplingBatchInfo"):
Got it! Sure, I will enforce a batched version of the test. Thanks for catching the bug.

2025-01-19 06:11 UTC, DreamGenX commented on python/sglang/srt/sampling/sampling_batch_info.py
> +            has_custom_logit_processor=has_custom_logit_processor,
Got it. I thought that if we parse it here, the lower level code would not have to deal with strings and caching (which seems like a workaround for the fact that we can't pass the deserialized logit processors to the API), and could just use the already deserialized python function.

In vLLM, the SamplingParams accepts [deserialized logit processors](https://github.com/vllm-project/vllm/blob/630eb5b5ce6ea59b6480440b7f6064be5ca71ae1/vllm/sampling_params.py#L155)

The deserialization happens [in the API layer](https://github.com/vllm-project/vllm/blob/630eb5b5ce6ea59b6480440b7f6064be5ca71ae1/vllm/entrypoints/openai/protocol.py#L169) and the lower level code can use the native python (deserialized) logit processors.

2025-01-19 07:48 UTC, hongpeng-guo commented
> We are almost there! Some final comments.

Thanks a lot for shepherding this! Just handled the comments. PTAL

2025-01-19 22:42 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_batch_info.py
> +        has_custom_logit_processor = any(r.custom_logit_processor for r in reqs)
we can even skip this for loop if custom logit process is not enabled by the server.

2025-01-19 22:43 UTC, merrymercy commented on python/sglang/srt/sampling/sampling_batch_info.py
> +        if not self.custom_logit_processor:
this seems not needed. If `self.custom_logit_processor` is None, why will it go to this function?

2025-01-19 22:44 UTC, merrymercy approved these changes

2025-01-19 22:46 UTC, merged

2025-01-19 22:52 UTC, merrymercy commented
@hongpeng-guo Thanks. It is merged.

Some follow-up items:
- Address the above two comments.
- Documentation. We can add some usage examples here https://github.com/sgl-project/sglang/blob/main/docs/references/sampling_params.md and it will be compiled as https://sgl-project.github.io/references/sampling_params.html

2025-01-20 00:43 UTC, hongpeng-guo commented on python/sglang/srt/sampling/sampling_batch_info.py
> +        if not self.custom_logit_processor:
Agreed, I can remove this or make it a simple assert.