Ata/grpc
sgl-project/sglang pull request #2478
Opened 2024-12-13 23:48 UTC by MrAta

## Motivation

## Modifications

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

2024-12-15 02:31 UTC, rkooo567 commented
Hi, @MrAta is this ready to be reviewed?

2024-12-15 02:31 UTC, rkooo567 commented
I am seeing some test fialures

2024-12-15 03:22 UTC, MrAta commented
> Hi, @MrAta is this ready to be reviewed?

Hey! No, it's not! It's still WIP and drafted. Will make it ready for review once done.

2024-12-15 20:04 UTC, MrAta commented
@rkooo567 It's ready for review now. Admittedly, the protos are minimal and need some iteration.

2024-12-16 08:12 UTC, Ying1123 commented
@MrAta From the current design, the http server and grpc server cannot be turned on simultaneously. Could you have a way to have both? One way is to use the original way to launch the HTTP server, and then launch the grpc server in the tokenizer manager when the first request comes (because only then will the event loop be created). The grpc server can use `get_event_loop` so that the HTTP and grpc server can be in the same event loop.

2024-12-18 09:14 UTC, MrAta commented
> @MrAta From the current design, the http server and grpc server cannot be turned on simultaneously. Could you have a way to have both? One way is to use the original way to launch the HTTP server, and then launch the grpc server in the tokenizer manager when the first request comes (because only then will the event loop be created). The grpc server can use `get_event_loop` so that the HTTP and grpc server can be in the same event loop.

@Ying1123 done.

2024-12-23 12:22 UTC, RinRin-32 commented
@MrAta Hello, any chance this could work with /generate using input_embeds? https://github.com/sgl-project/sglang/pull/2052

I think with gRPC, input_embeds based usage of Sglang would benefit hugely!

2024-12-23 20:55 UTC, MrAta commented
> @MrAta Hello, any chance this could work with /generate using input_embeds? #2052
> 
> I think with gRPC, input_embeds based usage of Sglang would benefit hugely!

Yes, that's part of the plan.

2024-12-25 01:22 UTC, RinRin-32 commented
I tried your implementation last night, turn out adapting to input_embeds is surprisingly painless. It involves modifying your completion.proto slightly as well as alteration to grpc server to take either prompt or input_embeds.

Issue I had was that it was awfully slow, likely because of the type conversion involved.

2024-12-26 16:56 UTC, rkooo567 requested changes
> Now when launching the server, it launches both a fastAPI and grpc server (when --grpc-port is provided).

Is this an intentional design? Is there a way to only launch grpc server?

Also a couple comments;
- I think we need to be a little more careful about the default values
- Also can you add tests?
- We should handle the client closes the connection (we probably want to abort the request in this case). Doesn't need to be done in this PR
- For missing / unsupported fields, can you give us a list and maybe create an issue to track?

2024-12-26 16:56 UTC, rkooo567 commented on python/pyproject.toml
> +srt = ["sglang[runtime_common]", "torch", "vllm>=0.6.3.post1,<=0.6.4.post1", "cuda-python", "flashinfer>=0.1.6", "grpcio==1.68.1", "grpcio-tools==1.68.1"]
is version restriction necessary?

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/bench_serving.py
> +        request = completion_pb2.CompletionRequest(
https://github.com/sgl-project/sglang/blob/2125898af5224464f5b5999e32a6cc93f442199c/python/sglang/bench_serving.py#L315

This doesn't seem to match (e.g., return logprobs or  **request_func_input.extra_request_body,)

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/bench_serving.py
> +        help="If not set, the default port is configured according to its default value for different LLM Inference Engines.",
Let's comment this is only for sglang backend and used only when grpc backend is used with --backend=="sglang-grpc"?

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/grpc_server.py
> +    async def Complete(
```suggestion
    async def complete(
```

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/proto/completion.proto
> +  bool ignore_eos = 12;
what are missing fields here? maybe add comments? (like add all fields and comment it out)

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/proto/completion.proto
> +message CompletionResponse {
why it very different from https://github.com/sgl-project/sglang/blob/2125898af5224464f5b5999e32a6cc93f442199c/python/sglang/srt/openai_api/protocol.py#L193?

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/proto/completion_pb2.py
> +# -*- coding: utf-8 -*-
how is it re-built whenever we merge a PR & change schema?

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/server.py
> +    1. HTTP server: A FastAPI server that routes requests to the engine. Alternatively, it can be a gRPC server.
Is "alternatively" the right word? Thought we are going to start both servers

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/grpc_server.py
> +                    "top_p": request.top_p,
this part is dangerous. grpc protobuf has a default value 0 for unset values, and it means this top_p, top_k could be different from the default (1 and -1 respectively)

I think we need some sort of mechanism to set the default value? one potential solution is to use optional field in protobuf and set the correct default value when they are not provided

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/grpc_server.py
> +                finished=True,
QQ: how does regular http completion request figure out if it is finished?

2024-12-26 16:56 UTC, rkooo567 commented on python/sglang/srt/grpc_server.py
> +            async for content in self.generate_request(adapted_request):
we need to hanadle the client closing the connection and abort the request (I think we can do it using context object). We can also do it as a follow up, and in that case, can you create a separate isuse?

2025-01-03 21:00 UTC, zifeitong commented
just want to chime in that grpc python server isn't very performant: https://github.com/LesnyRumcajs/grpc_bench/discussions/441

triton-inference-server removed grpc for performance reason:
https://github.com/triton-inference-server/python_backend/pull/42

2025-05-30 08:30 UTC, closed without merging