[Feature] Function Calling
sgl-project/sglang pull request #2544
Opened 2024-12-22 14:11 UTC by Tushar-ml

## Motivation

This PR provides support for function calling #2429 . Currently function tooling implemented for tokenizer apply_chat_template. Streaming not support as well for function tooling.

## Modifications

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

2024-12-25 15:31 UTC, HaoyuWang4188 commented on python/sglang/srt/openai_api/adapter.py
> +                    "content": ret_item["text"],
Maybe we can set content to be `"content": null` just like the [official OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat/create)?

2024-12-25 15:54 UTC, HaoyuWang4188 commented on python/sglang/srt/openai_api/adapter.py
> +                    "content": ret_item["text"],
```suggestion
                    "content": ret_item["text"] if(tool_calls is None) else None,
```

2024-12-25 15:56 UTC, HaoyuWang4188 commented on python/sglang/srt/openai_api/adapter.py
> +                ),
```suggestion
                message=ChatMessage(
                    role="assistant",
                    content=ret_item["text"] if (tool_calls is None) else None,
                    tool_calls=tool_calls,
                ),
```

2024-12-25 16:02 UTC, HaoyuWang4188 commented
Based on the communication in Slack, I have left some of my review comments. 😄
Would @Ying1123 please assign an official reviewer? Thank you!

2024-12-26 18:30 UTC, merrymercy reviewed
This looks good! I left a few comments.

2024-12-26 18:30 UTC, merrymercy commented on docs/references/function_calling.md
> + 1. Add Tool tag present in model in line 1055 `sglang/srt/openai_api/adapter.py`
the line number will change, so do not mention the exact line number.

2024-12-26 18:30 UTC, merrymercy commented on docs/references/function_calling.md
> +print(response)
1. (Necessary) Add a test case in https://github.com/sgl-project/sglang/blob/main/test/srt/test_openai_server.py. Assert the correctness of the output
2. (Optionally) convert this doc into an interactive notebook, similar to the others https://github.com/sgl-project/sglang/blob/main/docs/start/send_request.ipynb

2024-12-26 18:30 UTC, merrymercy commented on docs/references/function_calling.md
> + 2. Add support in parsing function for converting into tool calls `sglang/srt/utils.py`
mention the function name

2024-12-26 18:30 UTC, merrymercy commented on docs/references/function_calling.md
> +For adding support of more different architectures: \n
Reorganize this. Mention the usage first and then mention how to support a new model.

```
# Supported models
# Usage
# How to support a new model
```

2024-12-26 18:30 UTC, merrymercy commented on python/sglang/srt/openai_api/adapter.py
> +                    "content": ret_item["text"] if (tool_calls is None) else None,
```suggestion
                    "content": ret_item["text"] if tool_calls is None else None,
```

2024-12-26 18:30 UTC, merrymercy commented on python/sglang/srt/openai_api/adapter.py
> +                    content=ret_item["text"] if (tool_calls is None) else None,
```suggestion
                    content=ret_item["text"] if tool_calls is None else None,
```

2024-12-26 18:30 UTC, merrymercy commented on python/sglang/srt/openai_api/adapter.py
> +            "<|plugin|>" in text
1. Make these constants a list of constant strings
2. Put this list above `parse_tool_response` in `python/sglang/srt/utils.py`
3. Import this list here.

After this, people only need to update one file to support a new model.

2024-12-28 20:01 UTC, Tushar-ml commented
@merrymercy @Ying1123 The above comments have been resolved

2024-12-28 22:02 UTC, merrymercy requested changes
Some final minor comments! Then we can merge this.

2024-12-28 22:02 UTC, merrymercy commented on docs/backend/function_tooling.ipynb
> +    "# Function Tooling\n",
```suggestion
    "# Function Calling\n",
```

Update the title and filename in all places.
https://platform.openai.com/docs/guides/function-calling

2024-12-28 22:02 UTC, merrymercy commented on docs/references/function_calling.md
> +# Tools Calling
Merge `docs/references/function_calling.md` and `docs/backend/function_tooling.ipynb`.
I think we only need the content of this file but in the format of an interactive notebook.

The outline of this doc is very good!

2024-12-28 22:02 UTC, merrymercy commented on docs/references/function_calling.md
> +For adding support of more different models: \n
"\n" is not needed.

2024-12-29 02:58 UTC, Tushar-ml commented
Done @merrymercy

2024-12-29 05:58 UTC, merged