Allow release memory and later resume (compatible with CUDA graph)
sgl-project/sglang pull request #2630
Opened 2024-12-28 12:18 UTC by fzyzcjy

## Motivation

## Modifications

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

2024-12-29 00:50 UTC, fzyzcjy commented
(Well I only want to make it "not a draft" and not mean to @ so many people!)

2024-12-29 05:26 UTC, heiner commented
Hey @fzyzcjy - very impressive!

QQ: Do you think the `LD_PRELOAD` could be avoided via something like this?

* KV caches use a special allocation (not `torch.empty` or anything else that goes via PyTorch) right away. That special allocation gives a pointer + size which PyTorch can use via e.g. `torch.frombuffer`.
* The special allocation has an explicit deletion + recreation with the `cuMemAddressReserve` + `cuMemMap` trick used in `torch_memory_saver`?

This way this could even be written in ctypes, or otherwise be independent of PyTorch itself.

2024-12-29 07:42 UTC, fzyzcjy commented
@heiner Hi thank you for the suggestion!

Currently I do this because I also want to allow the model to be released as well, using one-liner `with memory_saver.region(): create_your_model_here`. 

Btw, I have updated how LD_PRELOAD is handled. Now users should not need to manually specify in command line.

(Also feel free to discuss in https://github.com/sgl-project/sglang/issues/2542, because I guess this comment will soon get folded once I push more commits...)

2025-01-13 06:45 UTC, merrymercy requested changes

2025-01-13 06:45 UTC, merrymercy commented on python/sglang/srt/models/base.py
> +class BaseCausalLM(nn.Module):
If we only need to add these two functions, we do not need to create a new base class here.

We can define two functions
 `def export_static_state(module)` and `def import_static_state(module, static_params)`

2025-01-13 06:45 UTC, merrymercy commented on python/sglang/srt/managers/io_struct.py
> +class ReleaseGPUOccupationReqInput:
Call it `ReleaseMemoryOccupationReqInput`. Rename all places (code, api name, etc).

2025-01-13 06:45 UTC, merrymercy commented on scripts/ci_install_dependency.sh
> +pip uninstall -y torch_memory_saver && pip install torch_memory_saver
use `--force-reinstall` instead of uninstall and reinstall?

2025-01-13 06:45 UTC, merrymercy commented on python/sglang/srt/server_args.py
> +            "--memory-saver",
```suggestion
            "--enable-memory-saver",
```

2025-01-13 06:45 UTC, merrymercy commented on python/sglang/srt/model_executor/model_runner.py
> +            memory_saver_adapter=self.memory_saver_adapter,
Can we do something similar to how we handle `get_model`, so we do not need to pass `memory_saver_adapter` as an argument to all kinds of memory pools.
```
        with self.memory_saver_adapter.region():
            self.req_to_token_pool = ReqToTokenPool(
```

2025-01-13 06:57 UTC, fzyzcjy commented on python/sglang/srt/models/base.py
> +class BaseCausalLM(nn.Module):
I was considering about customizability (e.g. a model may have different opinion about this), but yes this seems not needed at least today.

2025-01-13 13:16 UTC, merrymercy reviewed
Almost there! Just one final comment.

2025-01-13 13:16 UTC, merrymercy commented on python/sglang/srt/models/llama.py
>  class LlamaForCausalLM(nn.Module):
revert this?

2025-01-13 13:16 UTC, merrymercy commented on python/sglang/srt/model_executor/model_runner.py
> +            enable_memory_saver=self.server_args.enable_memory_saver,
See this comment https://github.com/sgl-project/sglang/pull/2630#discussion_r1912734551

2025-01-13 14:07 UTC, fzyzcjy commented on python/sglang/srt/model_executor/model_runner.py
> +            enable_memory_saver=self.server_args.enable_memory_saver,
Oops I misunderstood your question. I am worried maybe not, because it can happen that we do have some tensors inside req pool that needs to be preserved across memory release. (The torch_memory_saver does not offload things to cpu, instead it just throws away the content)

2025-01-13 14:15 UTC, fzyzcjy commented on python/sglang/srt/models/llama.py
>  class LlamaForCausalLM(nn.Module):
done (CI seems to be flaky)

2025-01-13 19:38 UTC, merged