[feat] Add math eval to CI nightly run
sgl-project/sglang pull request #2663
Opened 2024-12-30 07:55 UTC by XiaotongJiang

Fix forward for https://github.com/sgl-project/sglang/pull/2652

2024-12-31 18:16 UTC, XiaotongJiang commented
took a look of the recent flaky [nightly tests](https://github.com/sgl-project/sglang/actions/workflows/nightly-test.yml), theres some flakiness around gsm8k threshold for certain models, but the main contributor is human eval timing out from `evalplus.evaluate`, it seems they are using sync client in strict sequential manner [link](https://github.com/evalplus/evalplus/blob/master/evalplus/gen/util/openai_request.py#L7) and its slow. I didnt see a good way to speed it up, should we swap to other human eval lib? @Ying1123 @zhaochenyang20

2024-12-31 22:39 UTC, zhaochenyang20 commented
> took a look of the recent flaky [nightly tests](https://github.com/sgl-project/sglang/actions/workflows/nightly-test.yml), theres some flakiness around gsm8k threshold for certain models, but the main contributor is human eval timing out from `evalplus.evaluate`, it seems they are using sync client in strict sequential manner [link](https://github.com/evalplus/evalplus/blob/master/evalplus/gen/util/openai_request.py#L7) and its slow. I didnt see a good way to speed it up, should we swap to other human eval lib? @Ying1123 @zhaochenyang20

As we discussed, use `is_in_ci` to detect wether it's in the CI and only run `default_samll_model_name` on human eval.

Thanks, great job!

2025-01-01 18:36 UTC, zhaochenyang20 requested changes
Why disable human eval rather than add more time out?

2025-01-01 23:28 UTC, zhaochenyang20 commented
@XiaotongJiang LGTM

2025-01-01 23:29 UTC, zhaochenyang20 approved these changes

2025-01-01 23:29 UTC, merged