add new feature for llava-next-video
sgl-project/sglang pull request #417
Opened 2024-05-10 03:42 UTC by ZhangYuanhan-AI

llava-next-video: https://llava-vl.github.io/blog/2024-04-30-llava-next-video/

2024-05-11 06:52 UTC, hkunzhe commented on python/sglang/utils.py
> +import cv2
`opencv-python` should be added in `pyproject.toml`.

2024-05-11 07:38 UTC, hkunzhe commented on examples/quick_start/srt_example_llava_v.py
There are many user-defined paths and some parameters in argparse are not being used.

2024-05-12 04:07 UTC, merrymercy requested changes

2024-05-12 04:07 UTC, merrymercy commented on README.md
> +To refine and clean up the README you've provided for the SGLang project, I'll focus on improving clarity, organization, and conciseness. This includes providing clear installation instructions, simp
Revert the change to README.md

2024-05-12 04:07 UTC, merrymercy commented on python/pyproject.toml
> +       "zmq", "vllm==0.3.3", "interegular", "pydantic", "pillow", "outlines>=0.0.27"]
Recently, we moved to vllm==0.4.2, can you update accordingly?
There are only minor changes. You can change similar to the changes in this PR https://github.com/sgl-project/sglang/pull/380

2024-05-12 04:07 UTC, merrymercy commented on examples/demo/model_call.py
> +# from flask import Flask, request, jsonify
Rename `examples/demo` to `examples/llava_video`

2024-05-12 04:07 UTC, merrymercy commented on examples/quick_start/srt_example_llava_v.py
> +import argparse
move this to the beginning of the file.

2024-05-12 04:07 UTC, merrymercy commented on examples/quick_start/srt_example_llava_v.py
> +    parser.add_argument('--video-dir', type=str, default="/mnt/bn/vl-research/workspace/yhzhang/data/sora/", help='The directory to save the processed video files.')
It seems there are many personal paths. Can someone else easily run this script?
Maybe you can move all things under a single folder `examples/llava_video` and add a README.md with an example command that runs on your Q98Z4OTh8RwmDonc.mp4

2024-05-12 04:07 UTC, merrymercy commented on python/sglang/utils.py
> +# def encode_video_base64(video_path):
remove unused code.

2024-05-12 04:10 UTC, merrymercy commented on python/sglang/srt/managers/router/model_rpc.py
> +from typing import Any, Dict, List, Optional, Tuple, Union
merge this with L7

2024-05-12 05:57 UTC, closed without merging