Support data parallelism
sgl-project/sglang pull request #480
Opened 2024-05-27 01:38 UTC by Ying1123

2024-05-27 08:43 UTC, merrymercy requested changes

2024-05-27 08:43 UTC, merrymercy commented on python/sglang/srt/server_args.py
> +            help="Number of tensor parallelism group for data parallelism.",
```suggestion
            help="Data parallelism size.",
```

2024-05-27 08:43 UTC, merrymercy commented on python/sglang/srt/server_args.py
> +            default=ServerArgs.dispatch_method,
```suggestion
            default=ServerArgs.dispatch_method,
            help="Load balancing strategy for data parallelism.",
```

2024-05-27 08:43 UTC, merrymercy commented on python/sglang/srt/utils.py
> +    ret_ports = []
Use this new logic https://github.com/sgl-project/sglang/blob/55c16436273d4a42f7cfe342df5f10ad05a8d0fe/python/sglang/srt/utils.py#L141-L164

2024-05-28 03:58 UTC, Ying1123 commented on python/sglang/srt/managers/controller/manager_multi.py
> +        # TODO: parallelize this
```suggestion
```

2024-05-28 03:59 UTC, merrymercy approved these changes

2024-05-28 04:24 UTC, merged