Zeng
sgl-project/sglang pull request #545
Opened 2024-06-14 01:57 UTC by ZackZeng999

#532 I fixed this issue and some problems in test/srt/model

2024-06-14 03:45 UTC, Qubitium commented
@ZackZeng999  Please modify PR title so it better reflect what the code does.

2024-06-14 05:02 UTC, ZackZeng999 commented
> @ZackZeng999 Please modify PR title so it better reflect what the code does.

I wonder if this title is acceptable.

2024-06-15 05:48 UTC, Ying1123 requested changes
Please run `scripts/format.sh` to format the code.

2024-06-15 05:48 UTC, Ying1123 commented on test/srt/model/test_llama_low_api.py
> +from sglang.srt.managers.router.infer_batch import Batch
Did you ran the code after rebase to the most recent main? There is no `managers.router` anymore. `router` has been changed to `controller`.

2024-06-15 05:48 UTC, Ying1123 commented on test/srt/model/test_llama_low_api.py
> +    model = ModelRunner(server_args=ServerArgs(model_path=model_path),model_config=model_config, mem_fraction_static=0.8, tp_rank=tp_rank, tp_size=tp_size,gpu_id=0,nccl_port=28888,)
```suggestion
    model = ModelRunner(server_args=ServerArgs(model_path=model_path), model_config=model_config, mem_fraction_static=0.8, tp_rank=tp_rank, tp_size=tp_size, gpu_id=0, nccl_port=28888,)
```

2024-06-18 13:55 UTC, Qubitium commented on test/srt/model/test_llava_low_api.py
> +    image_path = "/content/drive/MyDrive/sglang/test/srt/example_image.png"
@ZackZeng999  This part of the test is not runnable by anyone other than you. Good to find an non-copyrighted image and put into repo for local testing.

2024-06-30 06:42 UTC, merged